//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApparatus.Lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectApparatus.Lang.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object.
        /// </summary>
        internal static string _object {
            get {
                return ResourceManager.GetString("object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjust Jump Height.
        /// </summary>
        internal static string adjust_jump_height {
            get {
                return ResourceManager.GetString("adjust_jump_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to modify your jump height..
        /// </summary>
        internal static string adjust_jump_height_descr {
            get {
                return ResourceManager.GetString("adjust_jump_height_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjust Sprint Speed.
        /// </summary>
        internal static string adjust_sprint_speed {
            get {
                return ResourceManager.GetString("adjust_sprint_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to modify your sprint speed..
        /// </summary>
        internal static string adjust_sprint_speed_descr {
            get {
                return ResourceManager.GetString("adjust_sprint_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjust Walk Speed.
        /// </summary>
        internal static string adjust_walk_speed {
            get {
                return ResourceManager.GetString("adjust_walk_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to modify your walk speed..
        /// </summary>
        internal static string adjust_walk_speed_descr {
            get {
                return ResourceManager.GetString("adjust_walk_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aggro Enemies.
        /// </summary>
        internal static string aggro_enemies {
            get {
                return ResourceManager.GetString("aggro_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Makes enemies target the selected player..
        /// </summary>
        internal static string aggro_enemies_descr_1 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doesn&apos;t work on most monsters, works best on Crawlers &amp; Spiders..
        /// </summary>
        internal static string aggro_enemies_descr_2 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Jetpacks Explode.
        /// </summary>
        internal static string all_jetpacks_explode {
            get {
                return ResourceManager.GetString("all_jetpacks_explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When a player tries to equip a jetpack they will be greeted with an explosion..
        /// </summary>
        internal static string all_jetpacks_explode_descr {
            get {
                return ResourceManager.GetString("all_jetpacks_explode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always Show Clock.
        /// </summary>
        internal static string always_show_clock {
            get {
                return ResourceManager.GetString("always_show_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displays the clock even when you are in the facility..
        /// </summary>
        internal static string always_show_clock_descr {
            get {
                return ResourceManager.GetString("always_show_clock_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attack Players at Deposit Desk.
        /// </summary>
        internal static string attack_players_at_deposit_desk {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forces the tentacle monster to attack, killing a nearby player..
        /// </summary>
        internal static string attack_players_at_deposit_desk_descr {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Big Loot.
        /// </summary>
        internal static string big_loot {
            get {
                return ResourceManager.GetString("big_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forces the game to render in full resolution..
        /// </summary>
        internal static string camera_res_descr_1 {
            get {
                return ResourceManager.GetString("camera_res_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;color=#ff0000&gt;You will need to leave the game for this to activate.&lt;/color&gt;.
        /// </summary>
        internal static string camera_res_descr_2 {
            get {
                return ResourceManager.GetString("camera_res_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Centered Indicators.
        /// </summary>
        internal static string centered_indicators {
            get {
                return ResourceManager.GetString("centered_indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displays the above indicators at the center of the screen..
        /// </summary>
        internal static string centered_indicators_descr {
            get {
                return ResourceManager.GetString("centered_indicators_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changelog.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Charge Any Item.
        /// </summary>
        internal static string charge_any_item {
            get {
                return ResourceManager.GetString("charge_any_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to put any grabbable item in the charger..
        /// </summary>
        internal static string charge_any_item_descr {
            get {
                return ResourceManager.GetString("charge_any_item_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close All Mechanical Doors.
        /// </summary>
        internal static string close_all_mechanical_doors {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closes all mechanical doors..
        /// </summary>
        internal static string close_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colors.
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credits.
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crosshair.
        /// </summary>
        internal static string crosshair {
            get {
                return ResourceManager.GetString("crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displays a crosshair on the screen..
        /// </summary>
        internal static string crosshair_descr {
            get {
                return ResourceManager.GetString("crosshair_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Damage.
        /// </summary>
        internal static string damage {
            get {
                return ResourceManager.GetString("damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Damages the player for a given amount..
        /// </summary>
        internal static string damage_descr {
            get {
                return ResourceManager.GetString("damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Days Left.
        /// </summary>
        internal static string days_left {
            get {
                return ResourceManager.GetString("days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dead Player List.
        /// </summary>
        internal static string dead_players {
            get {
                return ResourceManager.GetString("dead_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows a list of currently dead players..
        /// </summary>
        internal static string dead_players_descr {
            get {
                return ResourceManager.GetString("dead_players_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete All Enemies.
        /// </summary>
        internal static string delete_all_enemies {
            get {
                return ResourceManager.GetString("delete_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deletes all enemies..
        /// </summary>
        internal static string delete_all_enemies_descr {
            get {
                return ResourceManager.GetString("delete_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Demigod.
        /// </summary>
        internal static string demigod {
            get {
                return ResourceManager.GetString("demigod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically refills the selected player&apos;s health if below zero..
        /// </summary>
        internal static string demigod_descr {
            get {
                return ResourceManager.GetString("demigod_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Depth of Field.
        /// </summary>
        internal static string disable_dof {
            get {
                return ResourceManager.GetString("disable_dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disables the depth of field effect..
        /// </summary>
        internal static string disable_dof_descr {
            get {
                return ResourceManager.GetString("disable_dof_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Fall Damage.
        /// </summary>
        internal static string disable_fall_damage {
            get {
                return ResourceManager.GetString("disable_fall_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You no longer take fall damage..
        /// </summary>
        internal static string disable_fall_damage_descr {
            get {
                return ResourceManager.GetString("disable_fall_damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Fog.
        /// </summary>
        internal static string disable_fog {
            get {
                return ResourceManager.GetString("disable_fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disables the fog effect..
        /// </summary>
        internal static string disable_fog_descr {
            get {
                return ResourceManager.GetString("disable_fog_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Interact Cooldowns.
        /// </summary>
        internal static string disable_interact_cooldowns {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disables all interact cooldowns (e.g., noisemakers, toilets, etc)..
        /// </summary>
        internal static string disable_interact_cooldowns_descr {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Visor.
        /// </summary>
        internal static string disable_visor {
            get {
                return ResourceManager.GetString("disable_visor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disables the visor from your helmet in first person..
        /// </summary>
        internal static string disable_visor_descr {
            get {
                return ResourceManager.GetString("disable_visor_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Days Left.
        /// </summary>
        internal static string display_days_left {
            get {
                return ResourceManager.GetString("display_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows the time you have left to meet quota..
        /// </summary>
        internal static string display_days_left_descr {
            get {
                return ResourceManager.GetString("display_days_left_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Distance.
        /// </summary>
        internal static string display_distance {
            get {
                return ResourceManager.GetString("display_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows the distance between you and the entity..
        /// </summary>
        internal static string display_distance_esp_descr {
            get {
                return ResourceManager.GetString("display_distance_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Group Credits.
        /// </summary>
        internal static string display_group_credits {
            get {
                return ResourceManager.GetString("display_group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows how many credits you have..
        /// </summary>
        internal static string display_group_credits_descr {
            get {
                return ResourceManager.GetString("display_group_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Health.
        /// </summary>
        internal static string display_hp {
            get {
                return ResourceManager.GetString("display_hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows players&apos; health..
        /// </summary>
        internal static string display_hp_esp_descr {
            get {
                return ResourceManager.GetString("display_hp_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display Quota.
        /// </summary>
        internal static string display_quota {
            get {
                return ResourceManager.GetString("display_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows the current quota..
        /// </summary>
        internal static string display_quota_descr {
            get {
                return ResourceManager.GetString("display_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Is Speaking.
        /// </summary>
        internal static string display_speaking {
            get {
                return ResourceManager.GetString("display_speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows if the player is speaking..
        /// </summary>
        internal static string display_speaking_esp_descr {
            get {
                return ResourceManager.GetString("display_speaking_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Value.
        /// </summary>
        internal static string display_worth {
            get {
                return ResourceManager.GetString("display_worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows items&apos; value..
        /// </summary>
        internal static string display_worth_esp_descr {
            get {
                return ResourceManager.GetString("display_worth_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance.
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Door.
        /// </summary>
        internal static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doors.
        /// </summary>
        internal static string door_esp {
            get {
                return ResourceManager.GetString("door_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows all doors..
        /// </summary>
        internal static string door_esp_descr {
            get {
                return ResourceManager.GetString("door_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        internal static string enable_esp {
            get {
                return ResourceManager.GetString("enable_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enables the ESP..
        /// </summary>
        internal static string enable_esp_descr {
            get {
                return ResourceManager.GetString("enable_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enemy.
        /// </summary>
        internal static string enemy {
            get {
                return ResourceManager.GetString("enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enemy Distance Limit.
        /// </summary>
        internal static string enemy_distance_limit {
            get {
                return ResourceManager.GetString("enemy_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle to set the enemy distance limit..
        /// </summary>
        internal static string enemy_distance_limit_descr {
            get {
                return ResourceManager.GetString("enemy_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enemies.
        /// </summary>
        internal static string enemy_esp {
            get {
                return ResourceManager.GetString("enemy_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows all enemies..
        /// </summary>
        internal static string enemy_esp_descr {
            get {
                return ResourceManager.GetString("enemy_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entrance.
        /// </summary>
        internal static string entrance {
            get {
                return ResourceManager.GetString("entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ESP.
        /// </summary>
        internal static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Explode All Mines.
        /// </summary>
        internal static string explode_all_mines {
            get {
                return ResourceManager.GetString("explode_all_mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Explodes every single mine on the level..
        /// </summary>
        internal static string explode_all_mines_descr {
            get {
                return ResourceManager.GetString("explode_all_mines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FastLadder Climbing.
        /// </summary>
        internal static string fast_ladder_climbing {
            get {
                return ResourceManager.GetString("fast_ladder_climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instantly climbs up ladders..
        /// </summary>
        internal static string fast_ladder_climbing_descr {
            get {
                return ResourceManager.GetString("fast_ladder_climbing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field of View.
        /// </summary>
        internal static string fov {
            get {
                return ResourceManager.GetString("fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Give Credits.
        /// </summary>
        internal static string give_credits {
            get {
                return ResourceManager.GetString("give_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Give your group however many credits you want. (Doesn&apos;t apply to quota).
        /// </summary>
        internal static string give_credits_descr {
            get {
                return ResourceManager.GetString("give_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на God Mode.
        /// </summary>
        internal static string god_mode {
            get {
                return ResourceManager.GetString("god_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prevents you from taking any damage..
        /// </summary>
        internal static string god_mode_descr {
            get {
                return ResourceManager.GetString("god_mode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graphics.
        /// </summary>
        internal static string graphics {
            get {
                return ResourceManager.GetString("graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group Credits.
        /// </summary>
        internal static string group_credits {
            get {
                return ResourceManager.GetString("group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heal.
        /// </summary>
        internal static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heals the player for a given amount..
        /// </summary>
        internal static string heal_descr {
            get {
                return ResourceManager.GetString("heal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hear Everyone.
        /// </summary>
        internal static string hear_everyone {
            get {
                return ResourceManager.GetString("hear_everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to hear everyone no matter the distance..
        /// </summary>
        internal static string hear_everyone_descr {
            get {
                return ResourceManager.GetString("hear_everyone_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide Objects.
        /// </summary>
        internal static string hide_objects {
            get {
                return ResourceManager.GetString("hide_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hides spammed objects from the selected player..
        /// </summary>
        internal static string hide_objects_descr {
            get {
                return ResourceManager.GetString("hide_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinite Charge.
        /// </summary>
        internal static string infinite_charge {
            get {
                return ResourceManager.GetString("infinite_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prevents your items from losing any charge..
        /// </summary>
        internal static string infinite_charge_descr {
            get {
                return ResourceManager.GetString("infinite_charge_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinite Item Use.
        /// </summary>
        internal static string infinite_items {
            get {
                return ResourceManager.GetString("infinite_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to infinitely use items like the gift box and stun grenade. (Buggy).
        /// </summary>
        internal static string infinite_items_descr {
            get {
                return ResourceManager.GetString("infinite_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinite Shotgun Ammo.
        /// </summary>
        internal static string infinite_shotgun_ammo {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prevents you from out of ammo..
        /// </summary>
        internal static string infinite_shotgun_ammo_descr {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinite Stamina.
        /// </summary>
        internal static string infinite_stam {
            get {
                return ResourceManager.GetString("infinite_stam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prevents you from losing any stamina..
        /// </summary>
        internal static string infinite_stam_descr {
            get {
                return ResourceManager.GetString("infinite_stam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinite Zap Gun.
        /// </summary>
        internal static string infinite_zap_gun {
            get {
                return ResourceManager.GetString("infinite_zap_gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinitely stuns enemies with the zap-gun..
        /// </summary>
        internal static string infinite_zap_gun_descr {
            get {
                return ResourceManager.GetString("infinite_zap_gun_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instant Interactions.
        /// </summary>
        internal static string instant_interactions {
            get {
                return ResourceManager.GetString("instant_interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Makes all hold interactions instantaneous..
        /// </summary>
        internal static string instant_interactions_descr {
            get {
                return ResourceManager.GetString("instant_interactions_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interact Through Walls.
        /// </summary>
        internal static string interact_through_walls {
            get {
                return ResourceManager.GetString("interact_through_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to interact with anything through walls..
        /// </summary>
        internal static string interact_through_walls_descr {
            get {
                return ResourceManager.GetString("interact_through_walls_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item Distance Limit.
        /// </summary>
        internal static string item_distance_limit {
            get {
                return ResourceManager.GetString("item_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle to set the item distance limit..
        /// </summary>
        internal static string item_distance_limit_descr {
            get {
                return ResourceManager.GetString("item_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items.
        /// </summary>
        internal static string item_esp {
            get {
                return ResourceManager.GetString("item_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows all items..
        /// </summary>
        internal static string item_esp_descr {
            get {
                return ResourceManager.GetString("item_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kill.
        /// </summary>
        internal static string kill {
            get {
                return ResourceManager.GetString("kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kill All Enemies.
        /// </summary>
        internal static string kill_all_enemies {
            get {
                return ResourceManager.GetString("kill_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kills all enemies..
        /// </summary>
        internal static string kill_all_enemies_descr {
            get {
                return ResourceManager.GetString("kill_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kills the currently selected player..
        /// </summary>
        internal static string kill_descr {
            get {
                return ResourceManager.GetString("kill_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Land Ship.
        /// </summary>
        internal static string land_ship {
            get {
                return ResourceManager.GetString("land_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lands the ship..
        /// </summary>
        internal static string land_ship_descr {
            get {
                return ResourceManager.GetString("land_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Landmine.
        /// </summary>
        internal static string landmine {
            get {
                return ResourceManager.GetString("landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle to set the landmine distance limit..
        /// </summary>
        internal static string landmine_distance_limit_descr {
            get {
                return ResourceManager.GetString("landmine_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Landmines.
        /// </summary>
        internal static string landmine_esp {
            get {
                return ResourceManager.GetString("landmine_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows all landmines..
        /// </summary>
        internal static string landmine_esp_descr {
            get {
                return ResourceManager.GetString("landmine_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light Show.
        /// </summary>
        internal static string light_show {
            get {
                return ResourceManager.GetString("light_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rapidly turns on/off the light switch and TV..
        /// </summary>
        internal static string light_show_descr {
            get {
                return ResourceManager.GetString("light_show_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loot.
        /// </summary>
        internal static string loot {
            get {
                return ResourceManager.GetString("loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium Loot.
        /// </summary>
        internal static string medium_loot {
            get {
                return ResourceManager.GetString("medium_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Landmine Distance Limit.
        /// </summary>
        internal static string mine_distance_limit {
            get {
                return ResourceManager.GetString("mine_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Misc.
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Night Vision.
        /// </summary>
        internal static string night_vision {
            get {
                return ResourceManager.GetString("night_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to see in the dark..
        /// </summary>
        internal static string night_vision_descr {
            get {
                return ResourceManager.GetString("night_vision_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No More Credits.
        /// </summary>
        internal static string no_more_credits {
            get {
                return ResourceManager.GetString("no_more_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prevents your group from receiving any credits. (Doesn&apos;t apply to quota).
        /// </summary>
        internal static string no_more_credits_descr {
            get {
                return ResourceManager.GetString("no_more_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Noclip.
        /// </summary>
        internal static string noclip {
            get {
                return ResourceManager.GetString("noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to fly and clip through walls..
        /// </summary>
        internal static string noclip_descr {
            get {
                return ResourceManager.GetString("noclip_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object Spam.
        /// </summary>
        internal static string object_spam {
            get {
                return ResourceManager.GetString("object_spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spam places objects on the player to annoy/trap them..
        /// </summary>
        internal static string object_spam_descr {
            get {
                return ResourceManager.GetString("object_spam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One Hand All Objects.
        /// </summary>
        internal static string one_hand_all_objects {
            get {
                return ResourceManager.GetString("one_hand_all_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to one-hand any two-handed objects..
        /// </summary>
        internal static string one_hand_all_objects_descr {
            get {
                return ResourceManager.GetString("one_hand_all_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open All Mechanical Doors.
        /// </summary>
        internal static string open_all_mechanical_doors {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opens all mechanical doors..
        /// </summary>
        internal static string open_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Place Anywhere.
        /// </summary>
        internal static string place_anywhere {
            get {
                return ResourceManager.GetString("place_anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Place objects from the ship anywhere you want..
        /// </summary>
        internal static string place_anywhere_descr {
            get {
                return ResourceManager.GetString("place_anywhere_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Players.
        /// </summary>
        internal static string player_esp {
            get {
                return ResourceManager.GetString("player_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Players.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows all players..
        /// </summary>
        internal static string players_esp_descr {
            get {
                return ResourceManager.GetString("players_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Possess Nearest Enemy.
        /// </summary>
        internal static string possess_nearest_enemy {
            get {
                return ResourceManager.GetString("possess_nearest_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Possesses the nearest enemy. (Note: You will be visibily within the enemy.).
        /// </summary>
        internal static string possess_nearest_enemy_descr {
            get {
                return ResourceManager.GetString("possess_nearest_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profit Quota.
        /// </summary>
        internal static string profit_quota {
            get {
                return ResourceManager.GetString("profit_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Weight.
        /// </summary>
        internal static string remove_weight {
            get {
                return ResourceManager.GetString("remove_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removes speed limitations caused by item weight..
        /// </summary>
        internal static string remove_weight_descr {
            get {
                return ResourceManager.GetString("remove_weight_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Render Resolution.
        /// </summary>
        internal static string render_resolution {
            get {
                return ResourceManager.GetString("render_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Respawn.
        /// </summary>
        internal static string respawn {
            get {
                return ResourceManager.GetString("respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Respawns you. You will be invisible to both players and enemies..
        /// </summary>
        internal static string respawn_descr {
            get {
                return ResourceManager.GetString("respawn_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Language.
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected Player.
        /// </summary>
        internal static string selected_player {
            get {
                return ResourceManager.GetString("selected_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Self.
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Message.
        /// </summary>
        internal static string send_message_misc {
            get {
                return ResourceManager.GetString("send_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Anonymously sends a message in chat..
        /// </summary>
        internal static string send_message_misc_descr {
            get {
                return ResourceManager.GetString("send_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Message.
        /// </summary>
        internal static string send_message_player {
            get {
                return ResourceManager.GetString("send_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sends a message in chat as the selected player..
        /// </summary>
        internal static string send_message_player_descr {
            get {
                return ResourceManager.GetString("send_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Signal.
        /// </summary>
        internal static string send_signal {
            get {
                return ResourceManager.GetString("send_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remotely sends a signal..
        /// </summary>
        internal static string send_signal_descr {
            get {
                return ResourceManager.GetString("send_signal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sensitive Landmines.
        /// </summary>
        internal static string sensitive_landmines {
            get {
                return ResourceManager.GetString("sensitive_landmines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically detonates landmines when a player is in kill range..
        /// </summary>
        internal static string sensitive_landmines_descr {
            get {
                return ResourceManager.GetString("sensitive_landmines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set Quota.
        /// </summary>
        internal static string set_quota {
            get {
                return ResourceManager.GetString("set_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to set the quota. (Host only).
        /// </summary>
        internal static string set_quota_descr {
            get {
                return ResourceManager.GetString("set_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ship.
        /// </summary>
        internal static string ship {
            get {
                return ResourceManager.GetString("ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ships.
        /// </summary>
        internal static string ship_esp {
            get {
                return ResourceManager.GetString("ship_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows the ship..
        /// </summary>
        internal static string ship_esp_descr {
            get {
                return ResourceManager.GetString("ship_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small Loot.
        /// </summary>
        internal static string small_loot {
            get {
                return ResourceManager.GetString("small_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spam Message.
        /// </summary>
        internal static string spam_message_misc {
            get {
                return ResourceManager.GetString("spam_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Anonymously spams a message in chat..
        /// </summary>
        internal static string spam_message_misc_descr {
            get {
                return ResourceManager.GetString("spam_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spam Message.
        /// </summary>
        internal static string spam_message_player {
            get {
                return ResourceManager.GetString("spam_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spams the message in chat as the selected player..
        /// </summary>
        internal static string spam_message_player_descr {
            get {
                return ResourceManager.GetString("spam_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Ship.
        /// </summary>
        internal static string start_ship {
            get {
                return ResourceManager.GetString("start_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ship will leave the planet it&apos;s currently on..
        /// </summary>
        internal static string start_ship_descr {
            get {
                return ResourceManager.GetString("start_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam Hazards.
        /// </summary>
        internal static string steam_hazard {
            get {
                return ResourceManager.GetString("steam_hazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows all hazard zones..
        /// </summary>
        internal static string steam_hazard_esp_descr {
            get {
                return ResourceManager.GetString("steam_hazard_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam Profile.
        /// </summary>
        internal static string steam_profile {
            get {
                return ResourceManager.GetString("steam_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opens the selected player&apos;s steam profile in your overlay..
        /// </summary>
        internal static string steam_profile_descr {
            get {
                return ResourceManager.GetString("steam_profile_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steam Valve.
        /// </summary>
        internal static string steam_valve {
            get {
                return ResourceManager.GetString("steam_valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop Possessing.
        /// </summary>
        internal static string stop_possessing {
            get {
                return ResourceManager.GetString("stop_possessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stops possessing the currently possessed enemy..
        /// </summary>
        internal static string stop_possessing_descr {
            get {
                return ResourceManager.GetString("stop_possessing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Suicide.
        /// </summary>
        internal static string suicide {
            get {
                return ResourceManager.GetString("suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kills local player..
        /// </summary>
        internal static string suicide_descr {
            get {
                return ResourceManager.GetString("suicide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Taunt Slide.
        /// </summary>
        internal static string taunt_slide {
            get {
                return ResourceManager.GetString("taunt_slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to emote and move at the same time..
        /// </summary>
        internal static string taunt_slide_descr {
            get {
                return ResourceManager.GetString("taunt_slide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleport All Items.
        /// </summary>
        internal static string teleport_all_items {
            get {
                return ResourceManager.GetString("teleport_all_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleports all items on the planet to you..
        /// </summary>
        internal static string teleport_all_items_descr {
            get {
                return ResourceManager.GetString("teleport_all_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleport Enemies To.
        /// </summary>
        internal static string teleport_enemies_to {
            get {
                return ResourceManager.GetString("teleport_enemies_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleports all enemies to the currently selected player..
        /// </summary>
        internal static string teleport_enemies_to_descr {
            get {
                return ResourceManager.GetString("teleport_enemies_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleport Player To Ship.
        /// </summary>
        internal static string teleport_player_to_ship {
            get {
                return ResourceManager.GetString("teleport_player_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleports the selected into the ship. (Host only).
        /// </summary>
        internal static string teleport_player_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_player_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleport To.
        /// </summary>
        internal static string teleport_to {
            get {
                return ResourceManager.GetString("teleport_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleports you to the currently selected player..
        /// </summary>
        internal static string teleport_to_descr {
            get {
                return ResourceManager.GetString("teleport_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleport To Ship.
        /// </summary>
        internal static string teleport_to_ship {
            get {
                return ResourceManager.GetString("teleport_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teleports you into the ship..
        /// </summary>
        internal static string teleport_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terminal Noisemaker.
        /// </summary>
        internal static string terminal_noisemaker {
            get {
                return ResourceManager.GetString("terminal_noisemaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plays a very annoying noise from the terminal..
        /// </summary>
        internal static string terminal_noisemaker_descr {
            get {
                return ResourceManager.GetString("terminal_noisemaker_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press INSERT.
        /// </summary>
        internal static string tgl_insert {
            get {
                return ResourceManager.GetString("tgl_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thirdperson.
        /// </summary>
        internal static string thirdperson {
            get {
                return ResourceManager.GetString("thirdperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tooltips.
        /// </summary>
        internal static string tooltips {
            get {
                return ResourceManager.GetString("tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows information about the currently hovered menu item..
        /// </summary>
        internal static string tooltips_descr {
            get {
                return ResourceManager.GetString("tooltips_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turret.
        /// </summary>
        internal static string turret {
            get {
                return ResourceManager.GetString("turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turret Distance Limit.
        /// </summary>
        internal static string turret_distance_limit {
            get {
                return ResourceManager.GetString("turret_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle to set the turret distance limit..
        /// </summary>
        internal static string turret_distance_limit_descr {
            get {
                return ResourceManager.GetString("turret_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turrets.
        /// </summary>
        internal static string turret_esp {
            get {
                return ResourceManager.GetString("turret_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows all turrets..
        /// </summary>
        internal static string turret_esp_descr {
            get {
                return ResourceManager.GetString("turret_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve already unlocked all upgrades..
        /// </summary>
        internal static string u_alrd_unlc_all {
            get {
                return ResourceManager.GetString("u_alrd_unlc_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock All Suits.
        /// </summary>
        internal static string unlc_all_suits {
            get {
                return ResourceManager.GetString("unlc_all_suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocks All Suits..
        /// </summary>
        internal static string unlc_all_suits_descr {
            get {
                return ResourceManager.GetString("unlc_all_suits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock All Upgrades.
        /// </summary>
        internal static string unlc_all_upgrd_ship {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocks all ship upgrades..
        /// </summary>
        internal static string unlc_all_upgrd_ship_descr {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Grab Distance Limit.
        /// </summary>
        internal static string unlimited_grab_distance {
            get {
                return ResourceManager.GetString("unlimited_grab_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allows you to interact with anything no matter the distance..
        /// </summary>
        internal static string unlimited_grab_distance_descr {
            get {
                return ResourceManager.GetString("unlimited_grab_distance_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock.
        /// </summary>
        internal static string unlock {
            get {
                return ResourceManager.GetString("unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock All Doors.
        /// </summary>
        internal static string unlock_all_door {
            get {
                return ResourceManager.GetString("unlock_all_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocks all locked doors..
        /// </summary>
        internal static string unlock_all_door_descr {
            get {
                return ResourceManager.GetString("unlock_all_door_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upgrades.
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valve.
        /// </summary>
        internal static string valve {
            get {
                return ResourceManager.GetString("valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project Apparatus.
        /// </summary>
        internal static string watermark {
            get {
                return ResourceManager.GetString("watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to Project Apparatus.
        /// </summary>
        internal static string wlc_stp_1 {
            get {
                return ResourceManager.GetString("wlc_stp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you have suggestions, please create a pull request in the repo or reply to the UC thread..
        /// </summary>
        internal static string wlc_stp_2 {
            get {
                return ResourceManager.GetString("wlc_stp_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you find bugs, please provide some steps on how to reproduce the problem and create an issue or pull request in the repo or reply to the UC thread.
        /// </summary>
        internal static string wlc_stp_3 {
            get {
                return ResourceManager.GetString("wlc_stp_3", resourceCulture);
            }
        }
    }
}
