//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApparatus.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectApparatus.Lang.ru_RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты.
        /// </summary>
        internal static string _object {
            get {
                return ResourceManager.GetString("object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулировка высоты прыжка.
        /// </summary>
        internal static string adjust_jump_height {
            get {
                return ResourceManager.GetString("adjust_jump_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет изменять высоту прыжка..
        /// </summary>
        internal static string adjust_jump_height_descr {
            get {
                return ResourceManager.GetString("adjust_jump_height_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулировка скорости спринта.
        /// </summary>
        internal static string adjust_sprint_speed {
            get {
                return ResourceManager.GetString("adjust_sprint_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет изменять скорость спринта..
        /// </summary>
        internal static string adjust_sprint_speed_descr {
            get {
                return ResourceManager.GetString("adjust_sprint_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулировка скорости ходьбы.
        /// </summary>
        internal static string adjust_walk_speed {
            get {
                return ResourceManager.GetString("adjust_walk_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет изменять скорость ходьбы..
        /// </summary>
        internal static string adjust_walk_speed_descr {
            get {
                return ResourceManager.GetString("adjust_walk_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аггро-враги.
        /// </summary>
        internal static string aggro_enemies {
            get {
                return ResourceManager.GetString("aggro_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заставляет врагов сфокусировать внимание на выбранного игрока..
        /// </summary>
        internal static string aggro_enemies_descr_1 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не действует на большинство монстров, лучше всего работает на Бракена и Паука..
        /// </summary>
        internal static string aggro_enemies_descr_2 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все джетпаки взрываются.
        /// </summary>
        internal static string all_jetpacks_explode {
            get {
                return ResourceManager.GetString("all_jetpacks_explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда игрок попытается применить реактивный ранец, он взорвется..
        /// </summary>
        internal static string all_jetpacks_explode_descr {
            get {
                return ResourceManager.GetString("all_jetpacks_explode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всегда показывать часы.
        /// </summary>
        internal static string always_show_clock {
            get {
                return ResourceManager.GetString("always_show_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображает часы, даже когда вы находитесь в помещении..
        /// </summary>
        internal static string always_show_clock_descr {
            get {
                return ResourceManager.GetString("always_show_clock_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нападение на игроков возле сдачи квоты.
        /// </summary>
        internal static string attack_players_at_deposit_desk {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заставляет щупальца атаковать, убивая находящегося рядом игрока..
        /// </summary>
        internal static string attack_players_at_deposit_desk_descr {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большие предметы.
        /// </summary>
        internal static string big_loot {
            get {
                return ResourceManager.GetString("big_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заставляет игру рендерить полноценное разрешение..
        /// </summary>
        internal static string camera_res_descr_1 {
            get {
                return ResourceManager.GetString("camera_res_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;color=#ff0000&gt;Чтобы активировать эту функцию, вам нужно будет выйти из игры.&lt;/color&gt;.
        /// </summary>
        internal static string camera_res_descr_2 {
            get {
                return ResourceManager.GetString("camera_res_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатели в центре.
        /// </summary>
        internal static string centered_indicators {
            get {
                return ResourceManager.GetString("centered_indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображает вышеуказанные индикаторы в центре экрана..
        /// </summary>
        internal static string centered_indicators_descr {
            get {
                return ResourceManager.GetString("centered_indicators_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал изменений.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любой предмет можно зарядить.
        /// </summary>
        internal static string charge_any_item {
            get {
                return ResourceManager.GetString("charge_any_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет поместить в зарядное устройство любой предмет..
        /// </summary>
        internal static string charge_any_item_descr {
            get {
                return ResourceManager.GetString("charge_any_item_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть все двери требующие ключ.
        /// </summary>
        internal static string close_all_mechanical_doors {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрывает все двери которые требуют ключ..
        /// </summary>
        internal static string close_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета.
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработчики.
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прицел.
        /// </summary>
        internal static string crosshair {
            get {
                return ResourceManager.GetString("crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображает прицел в виде точки на экране..
        /// </summary>
        internal static string crosshair_descr {
            get {
                return ResourceManager.GetString("crosshair_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урон.
        /// </summary>
        internal static string damage {
            get {
                return ResourceManager.GetString("damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наносит игроку урон на заданное количество..
        /// </summary>
        internal static string damage_descr {
            get {
                return ResourceManager.GetString("damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дней осталось.
        /// </summary>
        internal static string days_left {
            get {
                return ResourceManager.GetString("days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список мертвых игроков.
        /// </summary>
        internal static string dead_players {
            get {
                return ResourceManager.GetString("dead_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображает на экране список мертвых игроков..
        /// </summary>
        internal static string dead_players_descr {
            get {
                return ResourceManager.GetString("dead_players_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить всех врагов.
        /// </summary>
        internal static string delete_all_enemies {
            get {
                return ResourceManager.GetString("delete_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаляет всех врагов на карте..
        /// </summary>
        internal static string delete_all_enemies_descr {
            get {
                return ResourceManager.GetString("delete_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полубог.
        /// </summary>
        internal static string demigod {
            get {
                return ResourceManager.GetString("demigod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически пополняет здоровье выбранного игрока, если оно ниже нуля..
        /// </summary>
        internal static string demigod_descr {
            get {
                return ResourceManager.GetString("demigod_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить глубину резкости.
        /// </summary>
        internal static string disable_dof {
            get {
                return ResourceManager.GetString("disable_dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключает эффект глубины резкости..
        /// </summary>
        internal static string disable_dof_descr {
            get {
                return ResourceManager.GetString("disable_dof_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить повреждение при падении.
        /// </summary>
        internal static string disable_fall_damage {
            get {
                return ResourceManager.GetString("disable_fall_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы больше не получаете урона от падения..
        /// </summary>
        internal static string disable_fall_damage_descr {
            get {
                return ResourceManager.GetString("disable_fall_damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить туман.
        /// </summary>
        internal static string disable_fog {
            get {
                return ResourceManager.GetString("disable_fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключает эффект тумана..
        /// </summary>
        internal static string disable_fog_descr {
            get {
                return ResourceManager.GetString("disable_fog_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить эффект взаимодействия.
        /// </summary>
        internal static string disable_interact_cooldowns {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключает все интерактивные кулдауны (например, шумелки, туалеты и т.д.)..
        /// </summary>
        internal static string disable_interact_cooldowns_descr {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить шлем.
        /// </summary>
        internal static string disable_visor {
            get {
                return ResourceManager.GetString("disable_visor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключает визор на шлеме от первого лица..
        /// </summary>
        internal static string disable_visor_descr {
            get {
                return ResourceManager.GetString("disable_visor_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать оставшиеся дни.
        /// </summary>
        internal static string display_days_left {
            get {
                return ResourceManager.GetString("display_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает время, оставшееся до выполнения квоты..
        /// </summary>
        internal static string display_days_left_descr {
            get {
                return ResourceManager.GetString("display_days_left_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать расстояние.
        /// </summary>
        internal static string display_distance {
            get {
                return ResourceManager.GetString("display_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает расстояние между вами и объектом..
        /// </summary>
        internal static string display_distance_esp_descr {
            get {
                return ResourceManager.GetString("display_distance_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать деньги.
        /// </summary>
        internal static string display_group_credits {
            get {
                return ResourceManager.GetString("display_group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает, сколько у вас денег для покупки..
        /// </summary>
        internal static string display_group_credits_descr {
            get {
                return ResourceManager.GetString("display_group_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать здоровье.
        /// </summary>
        internal static string display_hp {
            get {
                return ResourceManager.GetString("display_hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает здоровье игроков..
        /// </summary>
        internal static string display_hp_esp_descr {
            get {
                return ResourceManager.GetString("display_hp_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать стоимость лута на корабле.
        /// </summary>
        internal static string display_loot_in_ship {
            get {
                return ResourceManager.GetString("display_loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает стоимость всех предметов которые вы собрали, на корабле..
        /// </summary>
        internal static string display_loot_in_ship_descr {
            get {
                return ResourceManager.GetString("display_loot_in_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать квоту.
        /// </summary>
        internal static string display_quota {
            get {
                return ResourceManager.GetString("display_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает текущую квоту..
        /// </summary>
        internal static string display_quota_descr {
            get {
                return ResourceManager.GetString("display_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать говорит ли игрок.
        /// </summary>
        internal static string display_speaking {
            get {
                return ResourceManager.GetString("display_speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает, говорит ли игрок..
        /// </summary>
        internal static string display_speaking_esp_descr {
            get {
                return ResourceManager.GetString("display_speaking_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать стоимость.
        /// </summary>
        internal static string display_worth {
            get {
                return ResourceManager.GetString("display_worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает стоимость объектов..
        /// </summary>
        internal static string display_worth_esp_descr {
            get {
                return ResourceManager.GetString("display_worth_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдаление.
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дверь.
        /// </summary>
        internal static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двери.
        /// </summary>
        internal static string door_esp {
            get {
                return ResourceManager.GetString("door_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все двери..
        /// </summary>
        internal static string door_esp_descr {
            get {
                return ResourceManager.GetString("door_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить.
        /// </summary>
        internal static string enable_esp {
            get {
                return ResourceManager.GetString("enable_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включает ESP..
        /// </summary>
        internal static string enable_esp_descr {
            get {
                return ResourceManager.GetString("enable_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Враги.
        /// </summary>
        internal static string enemy {
            get {
                return ResourceManager.GetString("enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние до врага.
        /// </summary>
        internal static string enemy_distance_limit {
            get {
                return ResourceManager.GetString("enemy_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключите, чтобы включить отображение расстояния до противника..
        /// </summary>
        internal static string enemy_distance_limit_descr {
            get {
                return ResourceManager.GetString("enemy_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Враги.
        /// </summary>
        internal static string enemy_esp {
            get {
                return ResourceManager.GetString("enemy_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать всех враговю.
        /// </summary>
        internal static string enemy_esp_descr {
            get {
                return ResourceManager.GetString("enemy_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string entrance {
            get {
                return ResourceManager.GetString("entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP.
        /// </summary>
        internal static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взорвать мины.
        /// </summary>
        internal static string explode_all_mines {
            get {
                return ResourceManager.GetString("explode_all_mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взрывает все мины на уровне..
        /// </summary>
        internal static string explode_all_mines_descr {
            get {
                return ResourceManager.GetString("explode_all_mines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстрое лазание по лестнице.
        /// </summary>
        internal static string fast_ladder_climbing {
            get {
                return ResourceManager.GetString("fast_ladder_climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мгновенно взбирается по лестницам..
        /// </summary>
        internal static string fast_ladder_climbing_descr {
            get {
                return ResourceManager.GetString("fast_ladder_climbing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of View.
        /// </summary>
        internal static string fov {
            get {
                return ResourceManager.GetString("fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дать денег.
        /// </summary>
        internal static string give_credits {
            get {
                return ResourceManager.GetString("give_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дайте своей группе столько денег, сколько вы хотите. (Не относится к квоте).
        /// </summary>
        internal static string give_credits_descr {
            get {
                return ResourceManager.GetString("give_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бессмертие.
        /// </summary>
        internal static string god_mode {
            get {
                return ResourceManager.GetString("god_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предотвращает получение урона..
        /// </summary>
        internal static string god_mode_descr {
            get {
                return ResourceManager.GetString("god_mode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графика.
        /// </summary>
        internal static string graphics {
            get {
                return ResourceManager.GetString("graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги.
        /// </summary>
        internal static string group_credits {
            get {
                return ResourceManager.GetString("group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исцеление.
        /// </summary>
        internal static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вылечивает игрока на заданное количество..
        /// </summary>
        internal static string heal_descr {
            get {
                return ResourceManager.GetString("heal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слышать каждого.
        /// </summary>
        internal static string hear_everyone {
            get {
                return ResourceManager.GetString("hear_everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет слышать всех, независимо от расстояния..
        /// </summary>
        internal static string hear_everyone_descr {
            get {
                return ResourceManager.GetString("hear_everyone_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет мир!.
        /// </summary>
        internal static string hello_world {
            get {
                return ResourceManager.GetString("hello_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спрятать объекты.
        /// </summary>
        internal static string hide_objects {
            get {
                return ResourceManager.GetString("hide_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрывает заспамленные объекты от выбранного игрока..
        /// </summary>
        internal static string hide_objects_descr {
            get {
                return ResourceManager.GetString("hide_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесконечный заряд.
        /// </summary>
        internal static string infinite_charge {
            get {
                return ResourceManager.GetString("infinite_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предохраняет ваши вещи от потери заряда..
        /// </summary>
        internal static string infinite_charge_descr {
            get {
                return ResourceManager.GetString("infinite_charge_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесконечное использование предметов.
        /// </summary>
        internal static string infinite_items {
            get {
                return ResourceManager.GetString("infinite_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет бесконечно использовать такие предметы, как подарочная коробка и оглушающая граната. (Баг).
        /// </summary>
        internal static string infinite_items_descr {
            get {
                return ResourceManager.GetString("infinite_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесконечные патроны для дробовика.
        /// </summary>
        internal static string infinite_shotgun_ammo {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предотвращает прекращение расхода патронов..
        /// </summary>
        internal static string infinite_shotgun_ammo_descr {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесконечная стамина.
        /// </summary>
        internal static string infinite_stam {
            get {
                return ResourceManager.GetString("infinite_stam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предотвращает потерю выносливости..
        /// </summary>
        internal static string infinite_stam_descr {
            get {
                return ResourceManager.GetString("infinite_stam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесконечный Zap Gun.
        /// </summary>
        internal static string infinite_zap_gun {
            get {
                return ResourceManager.GetString("infinite_zap_gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесконечно оглушайте врагов с помощью zap-gun..
        /// </summary>
        internal static string infinite_zap_gun_descr {
            get {
                return ResourceManager.GetString("infinite_zap_gun_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мгновенное взаимодействие.
        /// </summary>
        internal static string instant_interactions {
            get {
                return ResourceManager.GetString("instant_interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делает все взаимодействия с задержкой мгновенными..
        /// </summary>
        internal static string instant_interactions_descr {
            get {
                return ResourceManager.GetString("instant_interactions_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взаимодействие через стены.
        /// </summary>
        internal static string interact_through_walls {
            get {
                return ResourceManager.GetString("interact_through_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет взаимодействовать с чем-либо через стены..
        /// </summary>
        internal static string interact_through_walls_descr {
            get {
                return ResourceManager.GetString("interact_through_walls_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невидимость.
        /// </summary>
        internal static string invisibility {
            get {
                return ResourceManager.GetString("invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игроки не смогут вас увидеть..
        /// </summary>
        internal static string invisibility_desc {
            get {
                return ResourceManager.GetString("invisibility_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние до лута.
        /// </summary>
        internal static string item_distance_limit {
            get {
                return ResourceManager.GetString("item_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключите, чтобы установить предельное расстояние между элементами..
        /// </summary>
        internal static string item_distance_limit_descr {
            get {
                return ResourceManager.GetString("item_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предметы.
        /// </summary>
        internal static string item_esp {
            get {
                return ResourceManager.GetString("item_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все предметы..
        /// </summary>
        internal static string item_esp_descr {
            get {
                return ResourceManager.GetString("item_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убийство.
        /// </summary>
        internal static string kill {
            get {
                return ResourceManager.GetString("kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убить всех врагов.
        /// </summary>
        internal static string kill_all_enemies {
            get {
                return ResourceManager.GetString("kill_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убивает всех врагов на карте..
        /// </summary>
        internal static string kill_all_enemies_descr {
            get {
                return ResourceManager.GetString("kill_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убивает выбранного игрока..
        /// </summary>
        internal static string kill_descr {
            get {
                return ResourceManager.GetString("kill_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приземлить корабль.
        /// </summary>
        internal static string land_ship {
            get {
                return ResourceManager.GetString("land_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приземляет корабль..
        /// </summary>
        internal static string land_ship_descr {
            get {
                return ResourceManager.GetString("land_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мина.
        /// </summary>
        internal static string landmine {
            get {
                return ResourceManager.GetString("landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключите, чтобы установить предельное расстояние до мины..
        /// </summary>
        internal static string landmine_distance_limit_descr {
            get {
                return ResourceManager.GetString("landmine_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать мины.
        /// </summary>
        internal static string landmine_esp {
            get {
                return ResourceManager.GetString("landmine_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает все мины.
        /// </summary>
        internal static string landmine_esp_descr {
            get {
                return ResourceManager.GetString("landmine_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Световое шоу.
        /// </summary>
        internal static string light_show {
            get {
                return ResourceManager.GetString("light_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень быстро включает и выключает свет на корабле..
        /// </summary>
        internal static string light_show_descr {
            get {
                return ResourceManager.GetString("light_show_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лут.
        /// </summary>
        internal static string loot {
            get {
                return ResourceManager.GetString("loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лут на корабле.
        /// </summary>
        internal static string loot_in_ship {
            get {
                return ResourceManager.GetString("loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний лут.
        /// </summary>
        internal static string medium_loot {
            get {
                return ResourceManager.GetString("medium_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние до мины.
        /// </summary>
        internal static string mine_distance_limit {
            get {
                return ResourceManager.GetString("mine_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разное.
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ночное зрение.
        /// </summary>
        internal static string night_vision {
            get {
                return ResourceManager.GetString("night_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет видеть в темноте. (Видно только вам).
        /// </summary>
        internal static string night_vision_descr {
            get {
                return ResourceManager.GetString("night_vision_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше никаких денег.
        /// </summary>
        internal static string no_more_credits {
            get {
                return ResourceManager.GetString("no_more_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не позволяет вашей группе получать деньги. (Не применяется к квоте).
        /// </summary>
        internal static string no_more_credits_descr {
            get {
                return ResourceManager.GetString("no_more_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полет сквозь стены.
        /// </summary>
        internal static string noclip {
            get {
                return ResourceManager.GetString("noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет летать и проходить сквозь стены..
        /// </summary>
        internal static string noclip_descr {
            get {
                return ResourceManager.GetString("noclip_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спам объектами.
        /// </summary>
        internal static string object_spam {
            get {
                return ResourceManager.GetString("object_spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спам помещает объекты на игрока, чтобы раздражать/заманивать его в ловушку..
        /// </summary>
        internal static string object_spam_descr {
            get {
                return ResourceManager.GetString("object_spam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двуручный предмет в слот.
        /// </summary>
        internal static string one_hand_all_objects {
            get {
                return ResourceManager.GetString("one_hand_all_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет брать в один слот, двуслотовые предметы.
        /// </summary>
        internal static string one_hand_all_objects_descr {
            get {
                return ResourceManager.GetString("one_hand_all_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть все шлюзы.
        /// </summary>
        internal static string open_all_mechanical_doors {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открывает все шлюзы, которые открываются через терминал..
        /// </summary>
        internal static string open_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разместить в любом месте.
        /// </summary>
        internal static string place_anywhere {
            get {
                return ResourceManager.GetString("place_anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разместите предметы с корабля в любом месте..
        /// </summary>
        internal static string place_anywhere_descr {
            get {
                return ResourceManager.GetString("place_anywhere_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игроки.
        /// </summary>
        internal static string player_esp {
            get {
                return ResourceManager.GetString("player_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игроки.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать всех игроков.
        /// </summary>
        internal static string players_esp_descr {
            get {
                return ResourceManager.GetString("players_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захватить управление над ближайшим врагом.
        /// </summary>
        internal static string possess_nearest_enemy {
            get {
                return ResourceManager.GetString("possess_nearest_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Овладевает ближайшим врагом. (Примечание: вы будете находиться внутри врага)..
        /// </summary>
        internal static string possess_nearest_enemy_descr {
            get {
                return ResourceManager.GetString("possess_nearest_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квота.
        /// </summary>
        internal static string profit_quota {
            get {
                return ResourceManager.GetString("profit_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без веса.
        /// </summary>
        internal static string remove_weight {
            get {
                return ResourceManager.GetString("remove_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устраняет ограничения скорости, вызванные весом предмета..
        /// </summary>
        internal static string remove_weight_descr {
            get {
                return ResourceManager.GetString("remove_weight_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное разрешение рендера.
        /// </summary>
        internal static string render_resolution {
            get {
                return ResourceManager.GetString("render_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Респаун.
        /// </summary>
        internal static string respawn {
            get {
                return ResourceManager.GetString("respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возобновляет вас. Вы будете невидимы как для игроков, так и для врагов. (Баг).
        /// </summary>
        internal static string respawn_descr {
            get {
                return ResourceManager.GetString("respawn_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать язык.
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный игрок.
        /// </summary>
        internal static string selected_player {
            get {
                return ResourceManager.GetString("selected_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для себя.
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        internal static string send_message_misc {
            get {
                return ResourceManager.GetString("send_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анонимно отправляет сообщение в чате..
        /// </summary>
        internal static string send_message_misc_descr {
            get {
                return ResourceManager.GetString("send_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение от имени игрока.
        /// </summary>
        internal static string send_message_player {
            get {
                return ResourceManager.GetString("send_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправляет сообщение в чат от имени выбранного игрока..
        /// </summary>
        internal static string send_message_player_descr {
            get {
                return ResourceManager.GetString("send_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послать сигнал.
        /// </summary>
        internal static string send_signal {
            get {
                return ResourceManager.GetString("send_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дистанционно посылает терминальный сигнал..
        /// </summary>
        internal static string send_signal_descr {
            get {
                return ResourceManager.GetString("send_signal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чувствительность мин.
        /// </summary>
        internal static string sensitive_landmines {
            get {
                return ResourceManager.GetString("sensitive_landmines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически взрывает мины, когда игрок находится в зоне поражения..
        /// </summary>
        internal static string sensitive_landmines_descr {
            get {
                return ResourceManager.GetString("sensitive_landmines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить квоту.
        /// </summary>
        internal static string set_quota {
            get {
                return ResourceManager.GetString("set_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет установить квоту. (Только для хоста).
        /// </summary>
        internal static string set_quota_descr {
            get {
                return ResourceManager.GetString("set_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корабль.
        /// </summary>
        internal static string ship {
            get {
                return ResourceManager.GetString("ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корабли.
        /// </summary>
        internal static string ship_esp {
            get {
                return ResourceManager.GetString("ship_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает корабль..
        /// </summary>
        internal static string ship_esp_descr {
            get {
                return ResourceManager.GetString("ship_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маленький лут.
        /// </summary>
        internal static string small_loot {
            get {
                return ResourceManager.GetString("small_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спам сообщениями.
        /// </summary>
        internal static string spam_message_misc {
            get {
                return ResourceManager.GetString("spam_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анонимно спамит сообщениями в чат..
        /// </summary>
        internal static string spam_message_misc_descr {
            get {
                return ResourceManager.GetString("spam_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спам сообщениями от имени игрока.
        /// </summary>
        internal static string spam_message_player {
            get {
                return ResourceManager.GetString("spam_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спамит сообщениями в чат от имени выбранного игрока..
        /// </summary>
        internal static string spam_message_player_descr {
            get {
                return ResourceManager.GetString("spam_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спавн врага.
        /// </summary>
        internal static string spawn_enemy {
            get {
                return ResourceManager.GetString("spawn_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawns a random enemy on the selected player..
        /// </summary>
        internal static string spawn_enemy_descr {
            get {
                return ResourceManager.GetString("spawn_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить корабль.
        /// </summary>
        internal static string start_ship {
            get {
                return ResourceManager.GetString("start_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корабль покинет планету, на которой находится в данный момент..
        /// </summary>
        internal static string start_ship_descr {
            get {
                return ResourceManager.GetString("start_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паровые вентили.
        /// </summary>
        internal static string steam_hazard {
            get {
                return ResourceManager.GetString("steam_hazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает все паровые вентили..
        /// </summary>
        internal static string steam_hazard_esp_descr {
            get {
                return ResourceManager.GetString("steam_hazard_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam профиль.
        /// </summary>
        internal static string steam_profile {
            get {
                return ResourceManager.GetString("steam_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открывает steam профиль выбранного игрока в вашем оверлее..
        /// </summary>
        internal static string steam_profile_descr {
            get {
                return ResourceManager.GetString("steam_profile_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паровой вентиль.
        /// </summary>
        internal static string steam_valve {
            get {
                return ResourceManager.GetString("steam_valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перестать управлять врагом.
        /// </summary>
        internal static string stop_possessing {
            get {
                return ResourceManager.GetString("stop_possessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прекращает одержимость врага, которым владеете в данный момент..
        /// </summary>
        internal static string stop_possessing_descr {
            get {
                return ResourceManager.GetString("stop_possessing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Харакири.
        /// </summary>
        internal static string suicide {
            get {
                return ResourceManager.GetString("suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убивает самого себя.
        /// </summary>
        internal static string suicide_descr {
            get {
                return ResourceManager.GetString("suicide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмоция во время движения.
        /// </summary>
        internal static string taunt_slide {
            get {
                return ResourceManager.GetString("taunt_slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет одновременно использовать эмоцию и двигаться..
        /// </summary>
        internal static string taunt_slide_descr {
            get {
                return ResourceManager.GetString("taunt_slide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортировать все предметы.
        /// </summary>
        internal static string teleport_all_items {
            get {
                return ResourceManager.GetString("teleport_all_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортирует к вам все предметы на планете..
        /// </summary>
        internal static string teleport_all_items_descr {
            get {
                return ResourceManager.GetString("teleport_all_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортировать врагов.
        /// </summary>
        internal static string teleport_enemies_to {
            get {
                return ResourceManager.GetString("teleport_enemies_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортирует всех врагов к выбранному игроку..
        /// </summary>
        internal static string teleport_enemies_to_descr {
            get {
                return ResourceManager.GetString("teleport_enemies_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепорт игрока на корабль.
        /// </summary>
        internal static string teleport_player_to_ship {
            get {
                return ResourceManager.GetString("teleport_player_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортирует выбранного на корабль. (Только для хозяина).
        /// </summary>
        internal static string teleport_player_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_player_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортировать.
        /// </summary>
        internal static string teleport_to {
            get {
                return ResourceManager.GetString("teleport_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортирует вас к выбранному игроку..
        /// </summary>
        internal static string teleport_to_descr {
            get {
                return ResourceManager.GetString("teleport_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепорт на корабль.
        /// </summary>
        internal static string teleport_to_ship {
            get {
                return ResourceManager.GetString("teleport_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепортирует вас на корабль..
        /// </summary>
        internal static string teleport_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спам терминалом.
        /// </summary>
        internal static string terminal_noisemaker {
            get {
                return ResourceManager.GetString("terminal_noisemaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проигрывает очень громкий и противный звук из терминала..
        /// </summary>
        internal static string terminal_noisemaker_descr {
            get {
                return ResourceManager.GetString("terminal_noisemaker_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите INSERT.
        /// </summary>
        internal static string tgl_insert {
            get {
                return ResourceManager.GetString("tgl_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Третье лицо.
        /// </summary>
        internal static string thirdperson {
            get {
                return ResourceManager.GetString("thirdperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всплывающие подсказки.
        /// </summary>
        internal static string tooltips {
            get {
                return ResourceManager.GetString("tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывает информацию о текущем наведенном элементе меню..
        /// </summary>
        internal static string tooltips_descr {
            get {
                return ResourceManager.GetString("tooltips_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турель.
        /// </summary>
        internal static string turret {
            get {
                return ResourceManager.GetString("turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние до турели.
        /// </summary>
        internal static string turret_distance_limit {
            get {
                return ResourceManager.GetString("turret_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключите, чтобы установить предельное расстояние до турели..
        /// </summary>
        internal static string turret_distance_limit_descr {
            get {
                return ResourceManager.GetString("turret_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турель.
        /// </summary>
        internal static string turret_esp {
            get {
                return ResourceManager.GetString("turret_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все турели.
        /// </summary>
        internal static string turret_esp_descr {
            get {
                return ResourceManager.GetString("turret_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже разблокировали все улучшения..
        /// </summary>
        internal static string u_alrd_unlc_all {
            get {
                return ResourceManager.GetString("u_alrd_unlc_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать все костюмы.
        /// </summary>
        internal static string unlc_all_suits {
            get {
                return ResourceManager.GetString("unlc_all_suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокирует все костюмы..
        /// </summary>
        internal static string unlc_all_suits_descr {
            get {
                return ResourceManager.GetString("unlc_all_suits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокировать все объекты корабля.
        /// </summary>
        internal static string unlc_all_upgrd_ship {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблокирует все объекты корабля..
        /// </summary>
        internal static string unlc_all_upgrd_ship_descr {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет ограничения по расстоянию захвата.
        /// </summary>
        internal static string unlimited_grab_distance {
            get {
                return ResourceManager.GetString("unlimited_grab_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволяет взаимодействовать с чем угодно, независимо от расстояния..
        /// </summary>
        internal static string unlimited_grab_distance_descr {
            get {
                return ResourceManager.GetString("unlimited_grab_distance_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string unlock {
            get {
                return ResourceManager.GetString("unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть все двери.
        /// </summary>
        internal static string unlock_all_door {
            get {
                return ResourceManager.GetString("unlock_all_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отпирает все запертые двери..
        /// </summary>
        internal static string unlock_all_door_descr {
            get {
                return ResourceManager.GetString("unlock_all_door_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улучшение.
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет вентиля.
        /// </summary>
        internal static string valve {
            get {
                return ResourceManager.GetString("valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект Apparatus.
        /// </summary>
        internal static string watermark {
            get {
                return ResourceManager.GetString("watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в проект Apparatus.
        /// </summary>
        internal static string wlc_stp_1 {
            get {
                return ResourceManager.GetString("wlc_stp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у вас есть предложения, пожалуйста, создайте pull request в репозитории или ответьте в теме UC..
        /// </summary>
        internal static string wlc_stp_2 {
            get {
                return ResourceManager.GetString("wlc_stp_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы обнаружили ошибки, пожалуйста, предоставьте шаги как воспроизвести проблему, и создайте тему или pull request в репозитории или ответьте в теме UC.
        /// </summary>
        internal static string wlc_stp_3 {
            get {
                return ResourceManager.GetString("wlc_stp_3", resourceCulture);
            }
        }
    }
}
