//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApparatus.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectApparatus.Lang.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 物品 的本地化字符串。
        /// </summary>
        internal static string _object {
            get {
                return ResourceManager.GetString("object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整跳跃高度 的本地化字符串。
        /// </summary>
        internal static string adjust_jump_height {
            get {
                return ResourceManager.GetString("adjust_jump_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你修改你的跳跃高度。 的本地化字符串。
        /// </summary>
        internal static string adjust_jump_height_descr {
            get {
                return ResourceManager.GetString("adjust_jump_height_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整冲刺速度 的本地化字符串。
        /// </summary>
        internal static string adjust_sprint_speed {
            get {
                return ResourceManager.GetString("adjust_sprint_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你修改你的冲刺速度。 的本地化字符串。
        /// </summary>
        internal static string adjust_sprint_speed_descr {
            get {
                return ResourceManager.GetString("adjust_sprint_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整行走速度 的本地化字符串。
        /// </summary>
        internal static string adjust_walk_speed {
            get {
                return ResourceManager.GetString("adjust_walk_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你修改你的行走速度。 的本地化字符串。
        /// </summary>
        internal static string adjust_walk_speed_descr {
            get {
                return ResourceManager.GetString("adjust_walk_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敌视玩家 的本地化字符串。
        /// </summary>
        internal static string aggro_enemies {
            get {
                return ResourceManager.GetString("aggro_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使敌人以选定玩家为目标。 的本地化字符串。
        /// </summary>
        internal static string aggro_enemies_descr_1 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对大多数怪物无效，对爬行者和蜘蛛效果最好。 的本地化字符串。
        /// </summary>
        internal static string aggro_enemies_descr_2 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有喷气背包都会爆炸 的本地化字符串。
        /// </summary>
        internal static string all_jetpacks_explode {
            get {
                return ResourceManager.GetString("all_jetpacks_explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当玩家试图装备或使用喷气背包时，迎接他们的将是爆炸 的本地化字符串。
        /// </summary>
        internal static string all_jetpacks_explode_descr {
            get {
                return ResourceManager.GetString("all_jetpacks_explode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 始终显示时钟 的本地化字符串。
        /// </summary>
        internal static string always_show_clock {
            get {
                return ResourceManager.GetString("always_show_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无论你在哪里始终会显示时钟 的本地化字符串。
        /// </summary>
        internal static string always_show_clock_descr {
            get {
                return ResourceManager.GetString("always_show_clock_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使商店触手怪物攻击 的本地化字符串。
        /// </summary>
        internal static string attack_players_at_deposit_desk {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迫使触手怪物攻击，杀死附近的一名玩家 的本地化字符串。
        /// </summary>
        internal static string attack_players_at_deposit_desk_descr {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高价值物品 的本地化字符串。
        /// </summary>
        internal static string big_loot {
            get {
                return ResourceManager.GetString("big_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制以全分辨率渲染游戏。 的本地化字符串。
        /// </summary>
        internal static string camera_res_descr_1 {
            get {
                return ResourceManager.GetString("camera_res_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=#ff0000&gt;你需要离开游戏才能激活&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string camera_res_descr_2 {
            get {
                return ResourceManager.GetString("camera_res_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目居中显示 的本地化字符串。
        /// </summary>
        internal static string centered_indicators {
            get {
                return ResourceManager.GetString("centered_indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示在屏幕中央 的本地化字符串。
        /// </summary>
        internal static string centered_indicators_descr {
            get {
                return ResourceManager.GetString("centered_indicators_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改日志 的本地化字符串。
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对任何物品充电 的本地化字符串。
        /// </summary>
        internal static string charge_any_item {
            get {
                return ResourceManager.GetString("charge_any_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许您将任何可抓取的项目放入充电器 的本地化字符串。
        /// </summary>
        internal static string charge_any_item_descr {
            get {
                return ResourceManager.GetString("charge_any_item_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有机械门 的本地化字符串。
        /// </summary>
        internal static string close_all_mechanical_doors {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有机械门 的本地化字符串。
        /// </summary>
        internal static string close_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金钱 的本地化字符串。
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准心 的本地化字符串。
        /// </summary>
        internal static string crosshair {
            get {
                return ResourceManager.GetString("crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在屏幕中间显示准心 的本地化字符串。
        /// </summary>
        internal static string crosshair_descr {
            get {
                return ResourceManager.GetString("crosshair_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害 的本地化字符串。
        /// </summary>
        internal static string damage {
            get {
                return ResourceManager.GetString("damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给予玩家指定伤害 的本地化字符串。
        /// </summary>
        internal static string damage_descr {
            get {
                return ResourceManager.GetString("damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余天数 的本地化字符串。
        /// </summary>
        internal static string days_left {
            get {
                return ResourceManager.GetString("days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 死亡玩家列表 的本地化字符串。
        /// </summary>
        internal static string dead_players {
            get {
                return ResourceManager.GetString("dead_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前死亡玩家列表 的本地化字符串。
        /// </summary>
        internal static string dead_players_descr {
            get {
                return ResourceManager.GetString("dead_players_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所有敌人 的本地化字符串。
        /// </summary>
        internal static string delete_all_enemies {
            get {
                return ResourceManager.GetString("delete_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所有敌人 的本地化字符串。
        /// </summary>
        internal static string delete_all_enemies_descr {
            get {
                return ResourceManager.GetString("delete_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动回血 的本地化字符串。
        /// </summary>
        internal static string demigod {
            get {
                return ResourceManager.GetString("demigod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果玩家的生命值低于一百，会自动恢复 的本地化字符串。
        /// </summary>
        internal static string demigod_descr {
            get {
                return ResourceManager.GetString("demigod_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用景深 的本地化字符串。
        /// </summary>
        internal static string disable_dof {
            get {
                return ResourceManager.GetString("disable_dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用景深效果 的本地化字符串。
        /// </summary>
        internal static string disable_dof_descr {
            get {
                return ResourceManager.GetString("disable_dof_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用摔伤 的本地化字符串。
        /// </summary>
        internal static string disable_fall_damage {
            get {
                return ResourceManager.GetString("disable_fall_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你将不会获得来自摔伤的伤害 的本地化字符串。
        /// </summary>
        internal static string disable_fall_damage_descr {
            get {
                return ResourceManager.GetString("disable_fall_damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用雾 的本地化字符串。
        /// </summary>
        internal static string disable_fog {
            get {
                return ResourceManager.GetString("disable_fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用雾效果 的本地化字符串。
        /// </summary>
        internal static string disable_fog_descr {
            get {
                return ResourceManager.GetString("disable_fog_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用交互冷却 的本地化字符串。
        /// </summary>
        internal static string disable_interact_cooldowns {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用所有交互冷却 (例如, 汽笛, 开枪, 等) 的本地化字符串。
        /// </summary>
        internal static string disable_interact_cooldowns_descr {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用查看器 的本地化字符串。
        /// </summary>
        internal static string disable_visor {
            get {
                return ResourceManager.GetString("disable_visor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以第一人称禁用头盔上的遮阳板。 的本地化字符串。
        /// </summary>
        internal static string disable_visor_descr {
            get {
                return ResourceManager.GetString("disable_visor_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余天数 的本地化字符串。
        /// </summary>
        internal static string display_days_left {
            get {
                return ResourceManager.GetString("display_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示剩余天数 的本地化字符串。
        /// </summary>
        internal static string display_days_left_descr {
            get {
                return ResourceManager.GetString("display_days_left_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示距离 的本地化字符串。
        /// </summary>
        internal static string display_distance {
            get {
                return ResourceManager.GetString("display_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示您和实体之间的距离 的本地化字符串。
        /// </summary>
        internal static string display_distance_esp_descr {
            get {
                return ResourceManager.GetString("display_distance_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金钱 的本地化字符串。
        /// </summary>
        internal static string display_group_credits {
            get {
                return ResourceManager.GetString("display_group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前金钱 的本地化字符串。
        /// </summary>
        internal static string display_group_credits_descr {
            get {
                return ResourceManager.GetString("display_group_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家血量 的本地化字符串。
        /// </summary>
        internal static string display_hp {
            get {
                return ResourceManager.GetString("display_hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示玩家血量 的本地化字符串。
        /// </summary>
        internal static string display_hp_esp_descr {
            get {
                return ResourceManager.GetString("display_hp_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船物品价值 的本地化字符串。
        /// </summary>
        internal static string display_loot_in_ship {
            get {
                return ResourceManager.GetString("display_loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前飞船内的物品价值 的本地化字符串。
        /// </summary>
        internal static string display_loot_in_ship_descr {
            get {
                return ResourceManager.GetString("display_loot_in_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谁在讲话 的本地化字符串。
        /// </summary>
        internal static string display_quota {
            get {
                return ResourceManager.GetString("display_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示玩家是否在说话 的本地化字符串。
        /// </summary>
        internal static string display_quota_descr {
            get {
                return ResourceManager.GetString("display_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谁在讲话 的本地化字符串。
        /// </summary>
        internal static string display_speaking {
            get {
                return ResourceManager.GetString("display_speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示玩家是否在说话 的本地化字符串。
        /// </summary>
        internal static string display_speaking_esp_descr {
            get {
                return ResourceManager.GetString("display_speaking_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品价值 的本地化字符串。
        /// </summary>
        internal static string display_worth {
            get {
                return ResourceManager.GetString("display_worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示物品的价值 的本地化字符串。
        /// </summary>
        internal static string display_worth_esp_descr {
            get {
                return ResourceManager.GetString("display_worth_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离 的本地化字符串。
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门 的本地化字符串。
        /// </summary>
        internal static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门 的本地化字符串。
        /// </summary>
        internal static string door_esp {
            get {
                return ResourceManager.GetString("door_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有门 的本地化字符串。
        /// </summary>
        internal static string door_esp_descr {
            get {
                return ResourceManager.GetString("door_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string en_US_descr {
            get {
                return ResourceManager.GetString("en_US_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string enable_esp {
            get {
                return ResourceManager.GetString("enable_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用追踪功能 的本地化字符串。
        /// </summary>
        internal static string enable_esp_descr {
            get {
                return ResourceManager.GetString("enable_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敌人 的本地化字符串。
        /// </summary>
        internal static string enemy {
            get {
                return ResourceManager.GetString("enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 狒狒鹰   的本地化字符串。
        /// </summary>
        internal static string enemy_Baboon_hawk {
            get {
                return ResourceManager.GetString("enemy_Baboon hawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 史莱姆   的本地化字符串。
        /// </summary>
        internal static string enemy_Blob {
            get {
                return ResourceManager.GetString("enemy_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地堡蜘蛛   的本地化字符串。
        /// </summary>
        internal static string enemy_Bunker_Spider {
            get {
                return ResourceManager.GetString("enemy_Bunker Spider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱脸虫   的本地化字符串。
        /// </summary>
        internal static string enemy_Centipede {
            get {
                return ResourceManager.GetString("enemy_Centipede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半身鱼   的本地化字符串。
        /// </summary>
        internal static string enemy_Crawler {
            get {
                return ResourceManager.GetString("enemy_Crawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敌人距离限制 的本地化字符串。
        /// </summary>
        internal static string enemy_distance_limit {
            get {
                return ResourceManager.GetString("enemy_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换以设定敌人的距离限制 的本地化字符串。
        /// </summary>
        internal static string enemy_distance_limit_descr {
            get {
                return ResourceManager.GetString("enemy_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敌人 的本地化字符串。
        /// </summary>
        internal static string enemy_esp {
            get {
                return ResourceManager.GetString("enemy_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换以设定敌人的距离限制 的本地化字符串。
        /// </summary>
        internal static string enemy_esp_descr {
            get {
                return ResourceManager.GetString("enemy_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑影   的本地化字符串。
        /// </summary>
        internal static string enemy_Flowerman {
            get {
                return ResourceManager.GetString("enemy_Flowerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巨人   的本地化字符串。
        /// </summary>
        internal static string enemy_ForestGiant {
            get {
                return ResourceManager.GetString("enemy_ForestGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 囤积虫   的本地化字符串。
        /// </summary>
        internal static string enemy_Hoarding_bug {
            get {
                return ResourceManager.GetString("enemy_Hoarding bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐盒小丑   的本地化字符串。
        /// </summary>
        internal static string enemy_Jester {
            get {
                return ResourceManager.GetString("enemy_Jester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鸟   的本地化字符串。
        /// </summary>
        internal static string enemy_Manticoil {
            get {
                return ResourceManager.GetString("enemy_Manticoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假人   的本地化字符串。
        /// </summary>
        internal static string enemy_Masked {
            get {
                return ResourceManager.GetString("enemy_Masked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无眼狗 的本地化字符串。
        /// </summary>
        internal static string enemy_MouthDog {
            get {
                return ResourceManager.GetString("enemy_MouthDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胡桃夹子   的本地化字符串。
        /// </summary>
        internal static string enemy_Nutcracker {
            get {
                return ResourceManager.GetString("enemy_Nutcracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孢子蜥蜴   的本地化字符串。
        /// </summary>
        internal static string enemy_Puffer {
            get {
                return ResourceManager.GetString("enemy_Puffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静电蜜蜂   的本地化字符串。
        /// </summary>
        internal static string enemy_Red_Locust_Bees {
            get {
                return ResourceManager.GetString("enemy_Red Locust Bees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹簧头   的本地化字符串。
        /// </summary>
        internal static string enemy_Spring {
            get {
                return ResourceManager.GetString("enemy_Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打击者   的本地化字符串。
        /// </summary>
        internal static string enemy_Thumper {
            get {
                return ResourceManager.GetString("enemy_Thumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入口 的本地化字符串。
        /// </summary>
        internal static string entrance {
            get {
                return ResourceManager.GetString("entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追踪 的本地化字符串。
        /// </summary>
        internal static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出口 的本地化字符串。
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引爆所有地雷 的本地化字符串。
        /// </summary>
        internal static string explode_all_mines {
            get {
                return ResourceManager.GetString("explode_all_mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引爆所有地雷 的本地化字符串。
        /// </summary>
        internal static string explode_all_mines_descr {
            get {
                return ResourceManager.GetString("explode_all_mines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速爬梯 的本地化字符串。
        /// </summary>
        internal static string fast_ladder_climbing {
            get {
                return ResourceManager.GetString("fast_ladder_climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即爬上梯子 的本地化字符串。
        /// </summary>
        internal static string fast_ladder_climbing_descr {
            get {
                return ResourceManager.GetString("fast_ladder_climbing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视野 的本地化字符串。
        /// </summary>
        internal static string fov {
            get {
                return ResourceManager.GetString("fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获得金钱 的本地化字符串。
        /// </summary>
        internal static string give_credits {
            get {
                return ResourceManager.GetString("give_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获得一定金钱 的本地化字符串。
        /// </summary>
        internal static string give_credits_descr {
            get {
                return ResourceManager.GetString("give_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无敌模式 的本地化字符串。
        /// </summary>
        internal static string god_mode {
            get {
                return ResourceManager.GetString("god_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你将不会扣血 的本地化字符串。
        /// </summary>
        internal static string god_mode_descr {
            get {
                return ResourceManager.GetString("god_mode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图形 的本地化字符串。
        /// </summary>
        internal static string graphics {
            get {
                return ResourceManager.GetString("graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金钱 的本地化字符串。
        /// </summary>
        internal static string group_credits {
            get {
                return ResourceManager.GetString("group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回血 的本地化字符串。
        /// </summary>
        internal static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复玩家一定血量 的本地化字符串。
        /// </summary>
        internal static string heal_descr {
            get {
                return ResourceManager.GetString("heal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 听到所有人说话 的本地化字符串。
        /// </summary>
        internal static string hear_everyone {
            get {
                return ResourceManager.GetString("hear_everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 听到所有人说话，无论他在哪里 的本地化字符串。
        /// </summary>
        internal static string hear_everyone_descr {
            get {
                return ResourceManager.GetString("hear_everyone_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好！ 的本地化字符串。
        /// </summary>
        internal static string hello_world {
            get {
                return ResourceManager.GetString("hello_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Objects 的本地化字符串。
        /// </summary>
        internal static string hide_objects {
            get {
                return ResourceManager.GetString("hide_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hides spammed objects from the selected player. 的本地化字符串。
        /// </summary>
        internal static string hide_objects_descr {
            get {
                return ResourceManager.GetString("hide_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限电量 的本地化字符串。
        /// </summary>
        internal static string infinite_charge {
            get {
                return ResourceManager.GetString("infinite_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的物品将不会失去任何电量 的本地化字符串。
        /// </summary>
        internal static string infinite_charge_descr {
            get {
                return ResourceManager.GetString("infinite_charge_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限物品 的本地化字符串。
        /// </summary>
        internal static string infinite_items {
            get {
                return ResourceManager.GetString("infinite_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限使用礼物盒、震撼弹 的本地化字符串。
        /// </summary>
        internal static string infinite_items_descr {
            get {
                return ResourceManager.GetString("infinite_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限散弹枪弹药 的本地化字符串。
        /// </summary>
        internal static string infinite_shotgun_ammo {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你将拥有无限弹药 的本地化字符串。
        /// </summary>
        internal static string infinite_shotgun_ammo_descr {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限耐力 的本地化字符串。
        /// </summary>
        internal static string infinite_stam {
            get {
                return ResourceManager.GetString("infinite_stam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你将不会失去任何耐力 的本地化字符串。
        /// </summary>
        internal static string infinite_stam_descr {
            get {
                return ResourceManager.GetString("infinite_stam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电击枪无限击晕 的本地化字符串。
        /// </summary>
        internal static string infinite_zap_gun {
            get {
                return ResourceManager.GetString("infinite_zap_gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用电击枪无限击昏敌人 的本地化字符串。
        /// </summary>
        internal static string infinite_zap_gun_descr {
            get {
                return ResourceManager.GetString("infinite_zap_gun_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交互瞬间完成 的本地化字符串。
        /// </summary>
        internal static string instant_interactions {
            get {
                return ResourceManager.GetString("instant_interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使所有保持互动动作瞬间完成 的本地化字符串。
        /// </summary>
        internal static string instant_interactions_descr {
            get {
                return ResourceManager.GetString("instant_interactions_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隔墙交互 的本地化字符串。
        /// </summary>
        internal static string interact_through_walls {
            get {
                return ResourceManager.GetString("interact_through_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你隔着墙和任何东西交互 的本地化字符串。
        /// </summary>
        internal static string interact_through_walls_descr {
            get {
                return ResourceManager.GetString("interact_through_walls_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐身 的本地化字符串。
        /// </summary>
        internal static string invisibility {
            get {
                return ResourceManager.GetString("invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他玩家将无法看到你 的本地化字符串。
        /// </summary>
        internal static string invisibility_desc {
            get {
                return ResourceManager.GetString("invisibility_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品距离限制 的本地化字符串。
        /// </summary>
        internal static string item_distance_limit {
            get {
                return ResourceManager.GetString("item_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换以设置物品距离限制 的本地化字符串。
        /// </summary>
        internal static string item_distance_limit_descr {
            get {
                return ResourceManager.GetString("item_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品 的本地化字符串。
        /// </summary>
        internal static string item_esp {
            get {
                return ResourceManager.GetString("item_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示物品 的本地化字符串。
        /// </summary>
        internal static string item_esp_descr {
            get {
                return ResourceManager.GetString("item_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死 的本地化字符串。
        /// </summary>
        internal static string kill {
            get {
                return ResourceManager.GetString("kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死所有敌人 的本地化字符串。
        /// </summary>
        internal static string kill_all_enemies {
            get {
                return ResourceManager.GetString("kill_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死所有敌人 的本地化字符串。
        /// </summary>
        internal static string kill_all_enemies_descr {
            get {
                return ResourceManager.GetString("kill_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死当前玩家 的本地化字符串。
        /// </summary>
        internal static string kill_descr {
            get {
                return ResourceManager.GetString("kill_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船着陆 的本地化字符串。
        /// </summary>
        internal static string land_ship {
            get {
                return ResourceManager.GetString("land_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船降落目标星球 的本地化字符串。
        /// </summary>
        internal static string land_ship_descr {
            get {
                return ResourceManager.GetString("land_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷 的本地化字符串。
        /// </summary>
        internal static string landmine {
            get {
                return ResourceManager.GetString("landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷 的本地化字符串。
        /// </summary>
        internal static string landmine_distance_limit_descr {
            get {
                return ResourceManager.GetString("landmine_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷 的本地化字符串。
        /// </summary>
        internal static string landmine_esp {
            get {
                return ResourceManager.GetString("landmine_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示地雷 的本地化字符串。
        /// </summary>
        internal static string landmine_esp_descr {
            get {
                return ResourceManager.GetString("landmine_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灯光闪烁 的本地化字符串。
        /// </summary>
        internal static string light_show {
            get {
                return ResourceManager.GetString("light_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速打开/关闭灯开关和电视 的本地化字符串。
        /// </summary>
        internal static string light_show_descr {
            get {
                return ResourceManager.GetString("light_show_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品 的本地化字符串。
        /// </summary>
        internal static string loot {
            get {
                return ResourceManager.GetString("loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船物品价值 的本地化字符串。
        /// </summary>
        internal static string loot_in_ship {
            get {
                return ResourceManager.GetString("loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米 的本地化字符串。
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中价值物品 的本地化字符串。
        /// </summary>
        internal static string medium_loot {
            get {
                return ResourceManager.GetString("medium_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高价值物品 的本地化字符串。
        /// </summary>
        internal static string mine_distance_limit {
            get {
                return ResourceManager.GetString("mine_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杂项 的本地化字符串。
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜视 的本地化字符串。
        /// </summary>
        internal static string night_vision {
            get {
                return ResourceManager.GetString("night_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让你在黑暗中也能看见 的本地化字符串。
        /// </summary>
        internal static string night_vision_descr {
            get {
                return ResourceManager.GetString("night_vision_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阻止团队获得余额 的本地化字符串。
        /// </summary>
        internal static string no_more_credits {
            get {
                return ResourceManager.GetString("no_more_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阻止您的团队获得任何钱(不适用于利润指标) 的本地化字符串。
        /// </summary>
        internal static string no_more_credits_descr {
            get {
                return ResourceManager.GetString("no_more_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞天遁地 的本地化字符串。
        /// </summary>
        internal static string noclip {
            get {
                return ResourceManager.GetString("noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住指定键位后即可穿越墙壁，按跳跃即可浮空 的本地化字符串。
        /// </summary>
        internal static string noclip_descr {
            get {
                return ResourceManager.GetString("noclip_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气笛   的本地化字符串。
        /// </summary>
        internal static string object_Airhorn {
            get {
                return ResourceManager.GetString("object_Airhorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子弹   的本地化字符串。
        /// </summary>
        internal static string object_Ammo {
            get {
                return ResourceManager.GetString("object_Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源装置   的本地化字符串。
        /// </summary>
        internal static string object_Apparatus {
            get {
                return ResourceManager.GetString("object_Apparatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钟   的本地化字符串。
        /// </summary>
        internal static string object_Bell {
            get {
                return ResourceManager.GetString("object_Bell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大螺栓   的本地化字符串。
        /// </summary>
        internal static string object_Big_bolt {
            get {
                return ResourceManager.GetString("object_Big bolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双筒望远镜   的本地化字符串。
        /// </summary>
        internal static string object_Binoculars {
            get {
                return ResourceManager.GetString("object_Binoculars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尸体   的本地化字符串。
        /// </summary>
        internal static string object_Body {
            get {
                return ResourceManager.GetString("object_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音响   的本地化字符串。
        /// </summary>
        internal static string object_Boombox {
            get {
                return ResourceManager.GetString("object_Boombox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瓶子   的本地化字符串。
        /// </summary>
        internal static string object_Bottles {
            get {
                return ResourceManager.GetString("object_Bottles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盒子   的本地化字符串。
        /// </summary>
        internal static string object_box {
            get {
                return ResourceManager.GetString("object_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷子   的本地化字符串。
        /// </summary>
        internal static string object_Brush {
            get {
                return ResourceManager.GetString("object_Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 糖果   的本地化字符串。
        /// </summary>
        internal static string object_Candy {
            get {
                return ResourceManager.GetString("object_Candy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收银机   的本地化字符串。
        /// </summary>
        internal static string object_Cash_register {
            get {
                return ResourceManager.GetString("object_Cash register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板   的本地化字符串。
        /// </summary>
        internal static string object_clipboard {
            get {
                return ResourceManager.GetString("object_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小丑喇叭   的本地化字符串。
        /// </summary>
        internal static string object_Clown_horn {
            get {
                return ResourceManager.GetString("object_Clown horn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大轴   的本地化字符串。
        /// </summary>
        internal static string object_Cog1 {
            get {
                return ResourceManager.GetString("object_Cog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喜剧   的本地化字符串。
        /// </summary>
        internal static string object_Comedy {
            get {
                return ResourceManager.GetString("object_Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 饼干模具   的本地化字符串。
        /// </summary>
        internal static string object_Cookie_mold_pan {
            get {
                return ResourceManager.GetString("object_Cookie mold pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 舒适的灯光   的本地化字符串。
        /// </summary>
        internal static string object_Cozy_Lights {
            get {
                return ResourceManager.GetString("object_Cozy Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 簸箕   的本地化字符串。
        /// </summary>
        internal static string object_Dust_pan {
            get {
                return ResourceManager.GetString("object_Dust pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打蛋器   的本地化字符串。
        /// </summary>
        internal static string object_Egg_beater {
            get {
                return ResourceManager.GetString("object_Egg beater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸缩梯   的本地化字符串。
        /// </summary>
        internal static string object_Extension_ladder {
            get {
                return ResourceManager.GetString("object_Extension ladder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 台灯   的本地化字符串。
        /// </summary>
        internal static string object_Fancy_lamp {
            get {
                return ResourceManager.GetString("object_Fancy lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手电筒   的本地化字符串。
        /// </summary>
        internal static string object_Flashlight {
            get {
                return ResourceManager.GetString("object_Flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 烧瓶   的本地化字符串。
        /// </summary>
        internal static string object_Flask {
            get {
                return ResourceManager.GetString("object_Flask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 礼物盒   的本地化字符串。
        /// </summary>
        internal static string object_Gift {
            get {
                return ResourceManager.GetString("object_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金条   的本地化字符串。
        /// </summary>
        internal static string object_Gold_bar {
            get {
                return ResourceManager.GetString("object_Gold bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金杯   的本地化字符串。
        /// </summary>
        internal static string object_Golden_cup {
            get {
                return ResourceManager.GetString("object_Golden cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鱼缸   的本地化字符串。
        /// </summary>
        internal static string object_Goldfish {
            get {
                return ResourceManager.GetString("object_Goldfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿色套装   的本地化字符串。
        /// </summary>
        internal static string object_Green_Suit {
            get {
                return ResourceManager.GetString("object_Green Suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吹风机   的本地化字符串。
        /// </summary>
        internal static string object_Hairdryer {
            get {
                return ResourceManager.GetString("object_Hairdryer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险套装   的本地化字符串。
        /// </summary>
        internal static string object_Hazard_Suit {
            get {
                return ResourceManager.GetString("object_Hazard Suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蜂巢   的本地化字符串。
        /// </summary>
        internal static string object_Hive {
            get {
                return ResourceManager.GetString("object_Hive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自制闪光弹   的本地化字符串。
        /// </summary>
        internal static string object_Homemade_flashbang {
            get {
                return ResourceManager.GetString("object_Homemade flashbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逆向传送器   的本地化字符串。
        /// </summary>
        internal static string object_Inverse_Teleporter {
            get {
                return ResourceManager.GetString("object_Inverse Teleporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南瓜灯   的本地化字符串。
        /// </summary>
        internal static string object_Jackolantern {
            get {
                return ResourceManager.GetString("object_Jackolantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泡菜 的本地化字符串。
        /// </summary>
        internal static string object_Jar_of_pickles {
            get {
                return ResourceManager.GetString("object_Jar of pickles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喷气背包   的本地化字符串。
        /// </summary>
        internal static string object_Jetpack {
            get {
                return ResourceManager.GetString("object_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钥匙   的本地化字符串。
        /// </summary>
        internal static string object_Key {
            get {
                return ResourceManager.GetString("object_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大轴   的本地化字符串。
        /// </summary>
        internal static string object_Large_axle {
            get {
                return ResourceManager.GetString("object_Large axle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光笔   的本地化字符串。
        /// </summary>
        internal static string object_Laser_pointer {
            get {
                return ResourceManager.GetString("object_Laser pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开锁器   的本地化字符串。
        /// </summary>
        internal static string object_Lockpicker {
            get {
                return ResourceManager.GetString("object_Lockpicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大喇叭   的本地化字符串。
        /// </summary>
        internal static string object_Loud_Horn {
            get {
                return ResourceManager.GetString("object_Loud Horn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 魔术7球   的本地化字符串。
        /// </summary>
        internal static string object_Magic_7_ball {
            get {
                return ResourceManager.GetString("object_Magic 7 ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大镜   的本地化字符串。
        /// </summary>
        internal static string object_Magnifying_glass {
            get {
                return ResourceManager.GetString("object_Magnifying glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掌上终端   的本地化字符串。
        /// </summary>
        internal static string object_Mapper {
            get {
                return ResourceManager.GetString("object_Mapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金属板   的本地化字符串。
        /// </summary>
        internal static string object_Metal_sheet {
            get {
                return ResourceManager.GetString("object_Metal sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 咖啡杯   的本地化字符串。
        /// </summary>
        internal static string object_Mug {
            get {
                return ResourceManager.GetString("object_Mug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大哥大   的本地化字符串。
        /// </summary>
        internal static string object_Old_phone {
            get {
                return ResourceManager.GetString("object_Old phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画作   的本地化字符串。
        /// </summary>
        internal static string object_Painting {
            get {
                return ResourceManager.GetString("object_Painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 睡衣套装   的本地化字符串。
        /// </summary>
        internal static string object_Pajama_Suit {
            get {
                return ResourceManager.GetString("object_Pajama Suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香水瓶   的本地化字符串。
        /// </summary>
        internal static string object_Perfume_bottle {
            get {
                return ResourceManager.GetString("object_Perfume bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药瓶   的本地化字符串。
        /// </summary>
        internal static string object_Pill_bottle {
            get {
                return ResourceManager.GetString("object_Pill bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 塑料鱼   的本地化字符串。
        /// </summary>
        internal static string object_Plastic_fish {
            get {
                return ResourceManager.GetString("object_Plastic fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毛绒睡衣公仔 的本地化字符串。
        /// </summary>
        internal static string object_Plushie_Pajama_Man {
            get {
                return ResourceManager.GetString("object_Plushie Pajama Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业手电筒   的本地化字符串。
        /// </summary>
        internal static string object_Pro_flashlight {
            get {
                return ResourceManager.GetString("object_Pro-flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷达发射器   的本地化字符串。
        /// </summary>
        internal static string object_Radar_booster {
            get {
                return ResourceManager.GetString("object_Radar-booster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唱片机   的本地化字符串。
        /// </summary>
        internal static string object_Record_Player {
            get {
                return ResourceManager.GetString("object_Record Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快乐水   的本地化字符串。
        /// </summary>
        internal static string object_Red_soda {
            get {
                return ResourceManager.GetString("object_Red soda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遥控器   的本地化字符串。
        /// </summary>
        internal static string object_Remote {
            get {
                return ResourceManager.GetString("object_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结婚戒指   的本地化字符串。
        /// </summary>
        internal static string object_Ring {
            get {
                return ResourceManager.GetString("object_Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浪漫之桌   的本地化字符串。
        /// </summary>
        internal static string object_Romantic_Table {
            get {
                return ResourceManager.GetString("object_Romantic Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橡胶鸭   的本地化字符串。
        /// </summary>
        internal static string object_Rubber_Ducky {
            get {
                return ResourceManager.GetString("object_Rubber Ducky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 霰弹枪   的本地化字符串。
        /// </summary>
        internal static string object_Shotgun {
            get {
                return ResourceManager.GetString("object_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铲子   的本地化字符串。
        /// </summary>
        internal static string object_Shovel {
            get {
                return ResourceManager.GetString("object_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淋浴器   的本地化字符串。
        /// </summary>
        internal static string object_Shower {
            get {
                return ResourceManager.GetString("object_Shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号发射器 的本地化字符串。
        /// </summary>
        internal static string object_Signal_Translator {
            get {
                return ResourceManager.GetString("object_Signal Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object Spam 的本地化字符串。
        /// </summary>
        internal static string object_spam {
            get {
                return ResourceManager.GetString("object_spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spam places objects on the player to annoy/trap them. 的本地化字符串。
        /// </summary>
        internal static string object_spam_descr {
            get {
                return ResourceManager.GetString("object_spam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喷漆   的本地化字符串。
        /// </summary>
        internal static string object_Spray_paint {
            get {
                return ResourceManager.GetString("object_Spray paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向盘 的本地化字符串。
        /// </summary>
        internal static string object_Steering_wheel {
            get {
                return ResourceManager.GetString("object_Steering wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 便签   的本地化字符串。
        /// </summary>
        internal static string object_Sticky_note {
            get {
                return ResourceManager.GetString("object_Sticky note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止标志   的本地化字符串。
        /// </summary>
        internal static string object_Stop_sign {
            get {
                return ResourceManager.GetString("object_Stop sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 震撼弹 的本地化字符串。
        /// </summary>
        internal static string object_Stun_grenade {
            get {
                return ResourceManager.GetString("object_Stun grenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌子 的本地化字符串。
        /// </summary>
        internal static string object_Table {
            get {
                return ResourceManager.GetString("object_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 茶壶   的本地化字符串。
        /// </summary>
        internal static string object_Tea_kettle {
            get {
                return ResourceManager.GetString("object_Tea kettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假牙   的本地化字符串。
        /// </summary>
        internal static string object_Teeth {
            get {
                return ResourceManager.GetString("object_Teeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送器 的本地化字符串。
        /// </summary>
        internal static string object_Teleporter {
            get {
                return ResourceManager.GetString("object_Teleporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电视   的本地化字符串。
        /// </summary>
        internal static string object_Television {
            get {
                return ResourceManager.GetString("object_Television", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲水马桶   的本地化字符串。
        /// </summary>
        internal static string object_Toilet {
            get {
                return ResourceManager.GetString("object_Toilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 牙膏   的本地化字符串。
        /// </summary>
        internal static string object_Toothpaste {
            get {
                return ResourceManager.GetString("object_Toothpaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 魔方   的本地化字符串。
        /// </summary>
        internal static string object_Toy_cube {
            get {
                return ResourceManager.GetString("object_Toy cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人玩具   的本地化字符串。
        /// </summary>
        internal static string object_Toy_robot {
            get {
                return ResourceManager.GetString("object_Toy robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悲剧   的本地化字符串。
        /// </summary>
        internal static string object_Tragedy {
            get {
                return ResourceManager.GetString("object_Tragedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 笑气   的本地化字符串。
        /// </summary>
        internal static string object_TZP_Inhalant {
            get {
                return ResourceManager.GetString("object_TZP-Inhalant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V 型发动机   的本地化字符串。
        /// </summary>
        internal static string object_V_type_engine {
            get {
                return ResourceManager.GetString("object_V-type engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对讲机   的本地化字符串。
        /// </summary>
        internal static string object_Walkie_talkie {
            get {
                return ResourceManager.GetString("object_Walkie-talkie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迎宾踏垫   的本地化字符串。
        /// </summary>
        internal static string object_Welcome_Mat {
            get {
                return ResourceManager.GetString("object_Welcome Mat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屁垫   的本地化字符串。
        /// </summary>
        internal static string object_Whoopie_cushion {
            get {
                return ResourceManager.GetString("object_Whoopie cushion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让行标志 的本地化字符串。
        /// </summary>
        internal static string object_Yield_sign {
            get {
                return ResourceManager.GetString("object_Yield sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电击枪   的本地化字符串。
        /// </summary>
        internal static string object_Zap_gun {
            get {
                return ResourceManager.GetString("object_Zap gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一只手拿物品 的本地化字符串。
        /// </summary>
        internal static string one_hand_all_objects {
            get {
                return ResourceManager.GetString("one_hand_all_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你单手操作任何双手操作的物体 的本地化字符串。
        /// </summary>
        internal static string one_hand_all_objects_descr {
            get {
                return ResourceManager.GetString("one_hand_all_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开所有机械门 的本地化字符串。
        /// </summary>
        internal static string open_all_mechanical_doors {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开所有机械门 的本地化字符串。
        /// </summary>
        internal static string open_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制摆放装置 的本地化字符串。
        /// </summary>
        internal static string place_anywhere {
            get {
                return ResourceManager.GetString("place_anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 把船上的物品放在任何你想放的地方 的本地化字符串。
        /// </summary>
        internal static string place_anywhere_descr {
            get {
                return ResourceManager.GetString("place_anywhere_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string player_esp {
            get {
                return ResourceManager.GetString("player_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string players_esp_descr {
            get {
                return ResourceManager.GetString("players_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制最近敌人 的本地化字符串。
        /// </summary>
        internal static string possess_nearest_enemy {
            get {
                return ResourceManager.GetString("possess_nearest_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制最近的敌人 的本地化字符串。
        /// </summary>
        internal static string possess_nearest_enemy_descr {
            get {
                return ResourceManager.GetString("possess_nearest_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 利润指标 的本地化字符串。
        /// </summary>
        internal static string profit_quota {
            get {
                return ResourceManager.GetString("profit_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无重力 的本地化字符串。
        /// </summary>
        internal static string remove_weight {
            get {
                return ResourceManager.GetString("remove_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除物品给你带来的重力 的本地化字符串。
        /// </summary>
        internal static string remove_weight_descr {
            get {
                return ResourceManager.GetString("remove_weight_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完全分辨率 的本地化字符串。
        /// </summary>
        internal static string render_resolution {
            get {
                return ResourceManager.GetString("render_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重生 的本地化字符串。
        /// </summary>
        internal static string respawn {
            get {
                return ResourceManager.GetString("respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重生(重生后将隐身) 的本地化字符串。
        /// </summary>
        internal static string respawn_descr {
            get {
                return ResourceManager.GetString("respawn_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄语 的本地化字符串。
        /// </summary>
        internal static string ru_RU_descr {
            get {
                return ResourceManager.GetString("ru_RU_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择语言 的本地化字符串。
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的玩家 的本地化字符串。
        /// </summary>
        internal static string selected_player {
            get {
                return ResourceManager.GetString("selected_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自己 的本地化字符串。
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送消息 的本地化字符串。
        /// </summary>
        internal static string send_message_misc {
            get {
                return ResourceManager.GetString("send_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送消息到聊天框 的本地化字符串。
        /// </summary>
        internal static string send_message_misc_descr {
            get {
                return ResourceManager.GetString("send_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送消息 的本地化字符串。
        /// </summary>
        internal static string send_message_player {
            get {
                return ResourceManager.GetString("send_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送消息到聊天框 的本地化字符串。
        /// </summary>
        internal static string send_message_player_descr {
            get {
                return ResourceManager.GetString("send_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送广播 的本地化字符串。
        /// </summary>
        internal static string send_signal {
            get {
                return ResourceManager.GetString("send_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送广播消息 的本地化字符串。
        /// </summary>
        internal static string send_signal_descr {
            get {
                return ResourceManager.GetString("send_signal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷将在杀伤范围内爆炸 的本地化字符串。
        /// </summary>
        internal static string sensitive_landmines {
            get {
                return ResourceManager.GetString("sensitive_landmines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当玩家在杀伤范围内时自动引爆地雷。 的本地化字符串。
        /// </summary>
        internal static string sensitive_landmines_descr {
            get {
                return ResourceManager.GetString("sensitive_landmines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置利润指标 的本地化字符串。
        /// </summary>
        internal static string set_quota {
            get {
                return ResourceManager.GetString("set_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置利润指标 (仅限主机) 的本地化字符串。
        /// </summary>
        internal static string set_quota_descr {
            get {
                return ResourceManager.GetString("set_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船 的本地化字符串。
        /// </summary>
        internal static string ship {
            get {
                return ResourceManager.GetString("ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船 的本地化字符串。
        /// </summary>
        internal static string ship_esp {
            get {
                return ResourceManager.GetString("ship_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示飞船 的本地化字符串。
        /// </summary>
        internal static string ship_esp_descr {
            get {
                return ResourceManager.GetString("ship_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低价值物品 的本地化字符串。
        /// </summary>
        internal static string small_loot {
            get {
                return ResourceManager.GetString("small_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送消息 的本地化字符串。
        /// </summary>
        internal static string spam_message_misc {
            get {
                return ResourceManager.GetString("spam_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送消息到聊天框 的本地化字符串。
        /// </summary>
        internal static string spam_message_misc_descr {
            get {
                return ResourceManager.GetString("spam_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送广播 的本地化字符串。
        /// </summary>
        internal static string spam_message_player {
            get {
                return ResourceManager.GetString("spam_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送广播消息 的本地化字符串。
        /// </summary>
        internal static string spam_message_player_descr {
            get {
                return ResourceManager.GetString("spam_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动飞船 的本地化字符串。
        /// </summary>
        internal static string start_ship {
            get {
                return ResourceManager.GetString("start_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动飞船 的本地化字符串。
        /// </summary>
        internal static string start_ship_descr {
            get {
                return ResourceManager.GetString("start_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蒸汽阀门 的本地化字符串。
        /// </summary>
        internal static string steam_hazard {
            get {
                return ResourceManager.GetString("steam_hazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蒸汽阀门 的本地化字符串。
        /// </summary>
        internal static string steam_hazard_esp_descr {
            get {
                return ResourceManager.GetString("steam_hazard_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam 档案 的本地化字符串。
        /// </summary>
        internal static string steam_profile {
            get {
                return ResourceManager.GetString("steam_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开当前玩家 Steam 档案 的本地化字符串。
        /// </summary>
        internal static string steam_profile_descr {
            get {
                return ResourceManager.GetString("steam_profile_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam Valve 的本地化字符串。
        /// </summary>
        internal static string steam_valve {
            get {
                return ResourceManager.GetString("steam_valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止控制 的本地化字符串。
        /// </summary>
        internal static string stop_possessing {
            get {
                return ResourceManager.GetString("stop_possessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止控制当前敌人 的本地化字符串。
        /// </summary>
        internal static string stop_possessing_descr {
            get {
                return ResourceManager.GetString("stop_possessing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自杀 的本地化字符串。
        /// </summary>
        internal static string suicide {
            get {
                return ResourceManager.GetString("suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击杀自己 的本地化字符串。
        /// </summary>
        internal static string suicide_descr {
            get {
                return ResourceManager.GetString("suicide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动时做表情 的本地化字符串。
        /// </summary>
        internal static string taunt_slide {
            get {
                return ResourceManager.GetString("taunt_slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你同时做表情和移动 的本地化字符串。
        /// </summary>
        internal static string taunt_slide_descr {
            get {
                return ResourceManager.GetString("taunt_slide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送所有物品 的本地化字符串。
        /// </summary>
        internal static string teleport_all_items {
            get {
                return ResourceManager.GetString("teleport_all_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将星球上所有物品传送到当前位置 的本地化字符串。
        /// </summary>
        internal static string teleport_all_items_descr {
            get {
                return ResourceManager.GetString("teleport_all_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送敌人 的本地化字符串。
        /// </summary>
        internal static string teleport_enemies_to {
            get {
                return ResourceManager.GetString("teleport_enemies_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将所有敌人传送至该玩家 的本地化字符串。
        /// </summary>
        internal static string teleport_enemies_to_descr {
            get {
                return ResourceManager.GetString("teleport_enemies_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮他回城 的本地化字符串。
        /// </summary>
        internal static string teleport_player_to_ship {
            get {
                return ResourceManager.GetString("teleport_player_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将他传送至飞船 (仅限主机) 的本地化字符串。
        /// </summary>
        internal static string teleport_player_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_player_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送到 的本地化字符串。
        /// </summary>
        internal static string teleport_to {
            get {
                return ResourceManager.GetString("teleport_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将你传送至选中的玩家 的本地化字符串。
        /// </summary>
        internal static string teleport_to_descr {
            get {
                return ResourceManager.GetString("teleport_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回城 的本地化字符串。
        /// </summary>
        internal static string teleport_to_ship {
            get {
                return ResourceManager.GetString("teleport_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送至飞船 的本地化字符串。
        /// </summary>
        internal static string teleport_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端噪音 的本地化字符串。
        /// </summary>
        internal static string terminal_noisemaker {
            get {
                return ResourceManager.GetString("terminal_noisemaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端将发出令人恼火的噪音 的本地化字符串。
        /// </summary>
        internal static string terminal_noisemaker_descr {
            get {
                return ResourceManager.GetString("terminal_noisemaker_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 INSERT | 卸载 Delete 的本地化字符串。
        /// </summary>
        internal static string tgl_insert {
            get {
                return ResourceManager.GetString("tgl_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三人称 的本地化字符串。
        /// </summary>
        internal static string thirdperson {
            get {
                return ResourceManager.GetString("thirdperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能具体提示 的本地化字符串。
        /// </summary>
        internal static string tooltips {
            get {
                return ResourceManager.GetString("tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前悬停菜单项的信息 的本地化字符串。
        /// </summary>
        internal static string tooltips_descr {
            get {
                return ResourceManager.GetString("tooltips_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炮台 的本地化字符串。
        /// </summary>
        internal static string turret {
            get {
                return ResourceManager.GetString("turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炮台距离限制 的本地化字符串。
        /// </summary>
        internal static string turret_distance_limit {
            get {
                return ResourceManager.GetString("turret_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换以设置炮台距离限制 的本地化字符串。
        /// </summary>
        internal static string turret_distance_limit_descr {
            get {
                return ResourceManager.GetString("turret_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炮台 的本地化字符串。
        /// </summary>
        internal static string turret_esp {
            get {
                return ResourceManager.GetString("turret_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炮台 的本地化字符串。
        /// </summary>
        internal static string turret_esp_descr {
            get {
                return ResourceManager.GetString("turret_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经解锁飞船所有物品了！ 的本地化字符串。
        /// </summary>
        internal static string u_alrd_unlc_all {
            get {
                return ResourceManager.GetString("u_alrd_unlc_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有套装 的本地化字符串。
        /// </summary>
        internal static string unlc_all_suits {
            get {
                return ResourceManager.GetString("unlc_all_suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有套装 的本地化字符串。
        /// </summary>
        internal static string unlc_all_suits_descr {
            get {
                return ResourceManager.GetString("unlc_all_suits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁飞船所有物品 的本地化字符串。
        /// </summary>
        internal static string unlc_all_upgrd_ship {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁飞船所有物品 的本地化字符串。
        /// </summary>
        internal static string unlc_all_upgrd_ship_descr {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无抓取距离限制 的本地化字符串。
        /// </summary>
        internal static string unlimited_grab_distance {
            get {
                return ResourceManager.GetString("unlimited_grab_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许您与任何东西进行交互，无论距离远近。 的本地化字符串。
        /// </summary>
        internal static string unlimited_grab_distance_descr {
            get {
                return ResourceManager.GetString("unlimited_grab_distance_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        internal static string unlock {
            get {
                return ResourceManager.GetString("unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有门 的本地化字符串。
        /// </summary>
        internal static string unlock_all_door {
            get {
                return ResourceManager.GetString("unlock_all_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有机械门 的本地化字符串。
        /// </summary>
        internal static string unlock_all_door_descr {
            get {
                return ResourceManager.GetString("unlock_all_door_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船 的本地化字符串。
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价值 的本地化字符串。
        /// </summary>
        internal static string valve {
            get {
                return ResourceManager.GetString("valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说 的本地化字符串。
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Apparatus 的本地化字符串。
        /// </summary>
        internal static string watermark {
            get {
                return ResourceManager.GetString("watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 Project Apparatus 的本地化字符串。
        /// </summary>
        internal static string wlc_stp_1 {
            get {
                return ResourceManager.GetString("wlc_stp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你有任何建议，请在Github项目提交Pull request或者在UC thread回复 的本地化字符串。
        /// </summary>
        internal static string wlc_stp_2 {
            get {
                return ResourceManager.GetString("wlc_stp_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你发现任何BUG，请在Github项目提交Pull request，需要提供操作步骤并说明如何复现问题 或者 在UC thread回复 的本地化字符串。
        /// </summary>
        internal static string wlc_stp_3 {
            get {
                return ResourceManager.GetString("wlc_stp_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文(简体) 的本地化字符串。
        /// </summary>
        internal static string zh_CN_descr {
            get {
                return ResourceManager.GetString("zh_CN_descr", resourceCulture);
            }
        }
    }
}
